### ISSUE TITLE
Issues with new Timetable module

### ISSUE THREAD

**Issue by Bounz** [genielabs/HomeGenie#112]
Hi @dmayard!
Thank you for the the new Timetable and Calendar modules in HG.
I've found some issues with these modules.
1. In "Thermostat" tab first three buttons are "Stop" (see screenshot), so I can't set thermostats to Heat mode.
2. While editing timetable I see buttons "Annuler" and "Valider" which are French version of "Cancel" and "Set" I assume. I'm using Russian locale on my computer, so HG tries to show Russian localized strings if they are available and otherwise it uses English locale. But here we see French what is disappointing as default HG language is English.
Also I think it's not a good solution to use non-English language for filenames and string constants in code (for example "tablehoraire.html", https://github.com/genielabs/HomeGenie/blob/b2966b8d6d4afcc0c8f3e61b7c1bd782eacd7c7c/BaseFiles/Common/html/pages/control/widgets/DaniMail/generic/tablehoraire.html#L227 where variable is named "texte" and it's value is "Arrêt").
![- -2015-01-27- -7 28 46](https://cloud.githubusercontent.com/assets/3062744/5913709/af1aed36-a5f9-11e4-9fae-f7024792e4e4.png)

**Comment by genielabs** [comment]
Hi @Bounz, this was just a preview and not all functionalities are working.
Agree about using english as default language as I've already told @dmayard. We will both be working on improving this widget, so thanks for advices. Hope you can help in testing timetables with a real z-wave thermostat because nor me or @dmayard have got one.

**Comment by dmayard** [comment]
I see with Gene and he agree to keep french name fot the widgets actually.
Ok Some text name are in french in the code. Et alors ...
Cheers
Dani

**Comment by dmayard** [comment]
I see with Gene and he agree to keep french name fot the widgets actually.
Ok Some text name are in french in the code. Et alors ... It's beta version
You can add the .json file for russian.


Cheers
Dani

**Comment by genielabs** [comment]
@Bounz @dmayard I did rewrote the Timetable widget from scratch.
Please @Bounz, can you help testing the thermostat functionalities?

**Comment by Bounz** [comment]
Hi, @genielabs.
I compiled HG using latest sources and configured a schedule for thermostats. But unfortunately Timetable app produces an error. Here is a corresponding line from log:
```
2015-01-29T23:55:02.0590870+03:00	HomeAutomation.HomeGenie.Automation	36	Automation Program	Runtime.Error	CR: Operator `==' cannot be applied to operands of type `bool' and `char'
```
Sorry, right now I have no ability to dig in deeper and find the roots of the problem.

**Comment by dmayard** [comment]
Hi Bounz,
Look at line 53 in module scheduling Number 36 :
// if (action.Value != action.Previous == '0')
For test you can mask that line. because it's compare the test != that is a bool and Value

Cheers
Dani

**Comment by Bounz** [comment]
Dani, I commented that line and after a couple of program recompiling everything began to work!
Thank you! I'll setup more full and precise schedule at the evening for both thermostats and will check that everything works as expected.

**Comment by genielabs** [comment]
@Bounz instead of commenting change it to

          if (action.Value != action.Previous)

since the purpose is to send commands to the thermostat only when a mode change is needed.

**Comment by genielabs** [comment]
just commited r472 with latest fixes and improvement to Timetable widget

**Comment by Bounz** [comment]
@genielabs Got an issue with the latest Timetable and thermostats.
I configured thermostat timetable 1 to heat from 00:00 to 07:00 and from 23:00 to 00:00. Then in thermostat widget I used this 1st timetable for work days. For other day types (weekends, holidays) I used 10th timetable which is actually empty (so the thermostat state is Off from 00:00 to 24:00).
Yesterday (Saturday) morning I noticed that thermostat didn't switched to off at midnight and continued to Heat till I switched it off manually.

**Comment by genielabs** [comment]
Hi @Bounz are you using a z-wave thermostat? Does the */api/HomeAutomation.ZWave/nodeid/Thermostat.ModeSet/Off* command actually work with your device?
I will check the Timetable program later. Just wanted to ask you if you can test the latest HG (either from source code or from the testing package on sourceforge r477).
I made some major changes to the thermostat handler. If it work, probably the specific ZWave.ME handler is not needed anymore as it will work with the generic one. Also implemented message queuing for battery powered devices.

**Comment by genielabs** [comment]
Hey @Bounz thanks for pointing to this, I fixed the issue and now Timetable is aware of the exception when crossing from one table type to another on midnight. Fix will be available in next commit.

**Comment by Bounz** [comment]
Hi @genielabs! Yes, I'm using Z-Wave Thermostats.
I tested the new generic thermostat handler and it seems that it works correctly, so there is no need in specific handler anymore.
I'll update Z-Wave.Me Floor Thermostat Widget later this week with some changes from updated generic thermostat widget (like coloured temperature knob, 0.5 degree knob step).
Also I'll test that Timetable issue with midnight and switching to another timetable.

**Comment by genielabs** [comment]
@Bounz you can use manufacturer specific as *MatchProperty/Value* in the widgets' *configuration.json* file.

**Comment by Bounz** [comment]
Great! I've made that, see https://github.com/genielabs/HomeGenie/pull/132.
