### ISSUE TITLE
Timetable Scheduler Issue

### ISSUE THREAD

**Issue by gcoupe** [genielabs/HomeGenie#113]
When Homegenie starts up, I get a message: "SunRise/SunSet Object reference not set to an instance of an object".
I'm running version 1.00 beta r466.

Thanks

**Comment by gcoupe** [comment]
OK - I think I've found out what was going on. The Timetable Scheduler references the jkutils for sunrise/sunset data - and the jkutils program was not enabled.

I think you can put this issue down to user ignorance...

**Comment by genielabs** [comment]
Timetable widget is going to be rewritten as it holds a bunch of issues.
