### ISSUE TITLE
r466 breaks all modules

### ISSUE THREAD

**Issue by bkenobi** [genielabs/HomeGenie#115]
As detailed in the following thread, several users have seen an issue where all modules (but not widgets) become "generic" upon update.  A reboot does not fix things and only a restore of backed up settings fixes things.

http://www.homegenie.it/forum/index.php?topic=681.0

**Comment by genielabs** [comment]
Could this be just an Internet Explorer related issue? Perhaps due to modules loading error.

**Comment by bkenobi** [comment]
I use FireFox and I tried loading the page several times since that was my first thought.  Also, I'm sure this was a HG issue since the lights did not function (scheduled control, scripts, etc) until I reloaded the settings.

**Comment by genielabs** [comment]
ok
