### ISSUE TITLE
GPIO04, GPIO17 & GPIO18 reporting ERROR on allocation

### ISSUE THREAD

**Issue by OnTheBayou** [genielabs/HomeGenie#117]
Current System:
- Raspberry B+ using Operating System IMG File downloaded from HomeGenie Website
- HomeGenie, Version 1.00 beta r474 installed via Update Manager
- Accessed via FireFox Ver 35.0.1

GPIO04, GPIO17 & GPIO18 generate error popup stating “GPIO ERROR: could not allocate some GPIO! Please set to OFF GPIO that are already in use.” whenever I attempt to assign them IN, IN+, IN- or OUT. However, GPIO21 through GPIO25 work fine as OUT. 
Any comments or suggestions will be greatly appreciated.

**Comment by genielabs** [comment]
On latest HomeGenie SD Card, GPIO04 is used for 1Wire bus. also GPIO17 and GPIO18 are already reserved for IR transceiver.
You can disable this by editing the **/etc/modules** file:

    # /etc/modules: kernel modules to load at boot time.
    #
    # This file contains the names of kernel modules that should be loaded
    # at boot time, one per line. Lines beginning with "#" are ignored.
    # Parameters can be specified after the module name.
    
    # Sound devices
    snd-bcm2835
    
    # GPIO infrared transceiver
    lirc_rpi gpio_in_pin=18 gpio_out_pin=17
    
    # 1-Wire devices
    w1-gpio
    # 1-Wire thermometer
    w1-therm

and adding a comment **#** to **lirc_rpi**, **w1-gpio**, **w1-therm** lines.

**Comment by OnTheBayou** [comment]
Thank You for the explanation and coding!
