### ISSUE TITLE
Dusk and Dawn Function.

### ISSUE THREAD

**Issue by gmccandless** [genielabs/HomeGenie#144]
The Sunrise / Sunset schedules are great and can be used for a number of lighting functions. However there are times when it's quite dark inside by the time Sunset arrives. Would it be possible to create a Dusk and Dawn function, where the time is say 20 minutes prior or post?

**Comment by genielabs** [comment]
see my reply here:
http://www.homegenie.it/forum/index.php?topic=790.msg4773#new
