### ISSUE TITLE
Request: Persistant Storage

### ISSUE THREAD

**Issue by JerryWorkman** [genielabs/HomeGenie#145]
When the HomeGenie service is restarted widget variables and some program variables are reset. For instance sensor "updatetime" . "Real" devices maintain state but virtual devices are reset to their startup state. Persistent storage would be useful in maintaining these values between restarts.

A simple key: value JSON store as part of the API would be fine.

**Comment by genielabs** [comment]
http://genielabs.github.io/HomeGenie/api/ape/a00014.html
