### ISSUE TITLE
Configuration parameters are reset if program is restarted

### ISSUE THREAD

**Issue by genielabs** [genielabs/HomeGenie#153]

**Comment by Bounz** [comment]
Also, HG doesn't update actual state of Z-Wave devices on startup. So, if I switch on the light, the widget in HG shows that the light is on. After that I shutdown HG, turn the light off and start HG again. The widget still shows that the light is on.

**Comment by genielabs** [comment]
Hi Bounz,

it seems that I was mistake about this bug. The problem was only affecting program 41 (MCP3008 Keypad) but for some reason, I could not replicate it anymore after changing some line of code and recompiling.
About the Z-Wave status update, this is expected since HG does not poll z-wave devices on startup.
But you can add an automation program that will do it:

(trigger code)

    return true;

(program code)

    When.SystemStarted( () =>
    {
        Modules
            .InDomain("HomeAutomation.ZWave")
            .Command("Basic.Get")
            .IterationDelay(0.25)
            .Execute();
        });
        return true;
    });
    Program.GoBackground();

Cheers,
g.
