### ISSUE TITLE
Zwave polling on linux doesn't works

### ISSUE THREAD

**Issue by temuccio** [genielabs/HomeGenie#158]
I have add one node zwave fibaro on my linux debian testing with USB ZME_UZB1.
When I change on/off state from HG, the switch node works fine.
When I change on/off state locally, the HG doesn't refresh the state (on windows works fine).
I have enabled Level Poll (with 15 seconds of intervall) and I have selected Level Poll in module Settings.

**Comment by genielabs** [comment]
is this stil happening?
