### ISSUE TITLE
Request: Add Zwave Devices

### ISSUE THREAD

**Issue by HellStorm666** [genielabs/HomeGenie#164]
Searched all json files with a script.
Found a few devices that I want to use that aren't in the json files.

TKB-TZ65D (dimmer)
Zwave.Me ZME-WallC-s (dimmer)

**Comment by HellStorm666** [comment]
xml file for TKB-TZ65D
http://www.pepper1.net/zwavedb/device/343/343-0118-0808-0808-06-03-28-01-03.xml

xml file for ZME-WallC-s
http://www.pepper1.net/zwavedb/device/554/554-0115-0100-0101-03-03-5c-01-00.xml

**Comment by genielabs** [comment]
https://github.com/genielabs/HomeGenie/blob/master/BaseFiles/Common/html/ext/zwave/pepper1db/0115_0100_0101.json

https://github.com/genielabs/HomeGenie/blob/master/BaseFiles/Common/html/ext/zwave/pepper1db/0118_0808_0808.json

g

**Comment by HellStorm666** [comment]
https://github.com/genielabs/HomeGenie/blob/master/BaseFiles/Common/html/ext/zwave/pepper1db/0118_0808_0808.json
is not correct. That is  "productName": "TZ65S" while the xml is <productName>TZ65D</productName>

image from https://github.com/genielabs/HomeGenie/blob/master/BaseFiles/Common/html/ext/zwave/pepper1db/0115_0100_0101.json is not correct.

**Comment by genielabs** [comment]
It seems that there are different products with same ID =/
http://www.pepper1.net/zwavedb/device/554/554-0115-0100-0101-03-03-5c-01-00.xml
http://www.pepper1.net/zwavedb/device/562/562-0115-0100-0101-03-03-5c-01-00.xml
so even if there were both json files, it would be trivial to determine the correct one to pick. Any suggestion is welcome.

**Comment by HellStorm666** [comment]
The TZ65D is only $5,- more than the TZ65S and gives the ability to dim instead of switch, but can also switch. 
The TZ65D is the most used therfore I guess.
So dropping the TZ65S would be best I think.

Also, The TZ65S isn't showed at http://www.pepper1.net/zwavedb/ under manufacturer Wenzhou TKB Control System CO.,LTD

**Comment by genielabs** [comment]
ok, added sorting by file name (asc) in the json file generator program, so among files with same ID, the latest should be generated.

**Comment by HellStorm666** [comment]
Maybe including the device type  (554 and 562 part) in the json could fix this problem.
So the json wont be 0115_0100_0101.json but 554_0115_0100_0101.json and 562_0115_0100_0101.json

**Comment by genielabs** [comment]
nevermind about sorting, 554 (the lowest) seem to be the one you need... anyway 554 and 562 is a counter field that cannot be derivated from the device data, so having this number in the file names will not help as is.

**Comment by HellStorm666** [comment]
Maybe ask pepper1 how it is possible that there are 2 devices with the same ID.
Should not be possible imho

**Comment by genielabs** [comment]
it should not... pheraps the first one is out of production. so the problem is that the manufacturer should have changed the id of the latter product.

**Comment by HellStorm666** [comment]
a well....
If you can't fix it, no problem.
Then I will replace the json file myself offline when I have HG installed ;)
