### ISSUE TITLE
Request: Add Pushbullet support

### ISSUE THREAD

**Issue by HellStorm666** [genielabs/HomeGenie#165]
I think it would be nice if it is possible to push messages from HG to pushover.
documents on it can be found here. https://docs.pushbullet.com/

If you think it is nice to have, but don't have the time to make it.
Maybe I can try to get it working?

**Comment by kevin789900** [comment]
Done via an app: http://www.homegenie.it/forum/index.php?topic=881.msg5299#msg5299
