### ISSUE TITLE
Sensor.Generic : bad value

### ISSUE THREAD

**Issue by noliono** [genielabs/HomeGenie#187]
I have two similar devices: Aeon lab multisensor, in general there is no value "Sensor.Generic" value for this 2 devices.
But often, HG use a value (temperature, lumi, humidity) for "Sensor.Generic". I could see (in HG full log) in the past, the device didn't send this value to HG.
So i suppose that HG "bug" ...

I could see that on the 2 devices.
The consequence for me, is that my alarm system "alarm" when this happen :/ 

(http://www.homegenie.it/forum/index.php?topic=987.0)

**Comment by genielabs** [comment]
ZWaveLib has now got its own repository, please have a check from there:
https://github.com/genielabs/zwave-lib-dotnet
