### ISSUE TITLE
Jquery.ui.datepicker call for "en" failing

### ISSUE THREAD

**Issue by Fmstrat** [genielabs/HomeGenie#191]
Error:

```
GET https://automation:21443/hg/html/js/i18n/jquery.ui.datepicker-en.js?_=1438288258314 404 Not Found   41ms
```

Existing files:

```
root@automation:/usr/local/bin/homegenie/html/js/i18n# ls -l jquery.ui.datepicker-en*
-rw-rw-r-- 1 pi pi 897 May 31 12:03 jquery.ui.datepicker-en-AU.js
-rw-rw-r-- 1 pi pi 874 May 31 12:03 jquery.ui.datepicker-en-GB.js
-rw-rw-r-- 1 pi pi 899 May 31 12:03 jquery.ui.datepicker-en-NZ.js
root@automation:/usr/local/bin/homegenie/html/js/i18n#
```

This is from the deb package installed on a Raspberry Pi.

Potential offending line: https://github.com/genielabs/HomeGenie/blob/da9997e761b7f0d01cc85c516297055c91093e0d/BaseFiles/Common/html/pages/control/widgets/homegenie/generic/timetable.js#L115

This is based off this forum entry stating that `en` is the default internal localization, thus `userLang` should be converted to `""` in that line if `en`/`en-US` is the default language: http://forum.jquery.com/topic/missing-jquery-ui-datepicker-en-js-file

**Comment by pcguru** [comment]
Similar problem with the datebox component.
https://github.com/genielabs/HomeGenie/pull/265
