### ISSUE TITLE
Repeated HG login prompts on mobile chrome browsers

### ISSUE THREAD

**Issue by kevin789900** [genielabs/HomeGenie#195]
On android and ios chrome browser the HG login prompt pops up for me repeatedly.  This is very annoying and makes it hard to even close the HG tab frequently.  It pops up as I try to type or cancel into the first popup.  I have posted about this in other threads but have not gotten a solution.  Tried adding the user/password to the URL, this helps a bit on android, but the problem still pops up after going away from the browser and returning.  

I access HG through my router so a long password is a must for security but difficult in this situation.

Can you make an option to use a webpage form (like most websites) for the password instead of popup?  Also, would it be good to allow us to change username from admin to something more secure?

**Comment by gitbjo** [comment]
I face the same problem with Opera on Android, it's not usable you can't get rid of the login prompt. Btw with Opera the widgets are screwed up.

I found a workaround using the standard Android 5.0 browser and once entered the credentials, it still stay as modal dialog, but you can get rid of it by pressing the back button several times.

**Comment by amselem** [comment]
I think this was already fixed with: https://github.com/genielabs/mig-service-dotnet/pull/8
