### ISSUE TITLE
Request: add ZWave Heal Network funcitonality

### ISSUE THREAD

**Issue by genielabs** [genielabs/HomeGenie#199]

**Comment by genielabs** [comment]
@dmayard can you help testing the new functionality from the zwave-rework branch?
https://github.com/genielabs/HomeGenie/tree/zwave-rework

**Comment by dmayard** [comment]
OK Gene. I willl pull that branch for test.
Cheers Dani

**Comment by dmayard** [comment]
I have made some tests Heal Node works for the list of local nodes detected. But do you implement the statistics also (Repeated messages; number of dead lines, etc...) ? And I have one request : mark and show in the title barre of the widget when it's have timeout as the node is dead or alive (Small icon green or red), or only mark in case of Dead.
