### ISSUE TITLE
Enhance Web api to query device status

### ISSUE THREAD

**Issue by Jens1234** [genielabs/HomeGenie#206]
Hi Gene,

It would be helpful to be able to query the device status also via the WEB API.

Please see also 

http://sourceforge.net/p/homegenie/discussion/general/thread/82896dcb/

This would be helpful on screens/devices like iOS to build  a controller (like a controller on the wall).

Thanks
Regards
Jens

**Comment by genielabs** [comment]
Hey Jens see r497 news:

- Enhanced parameter statistics now holding up to 1 day of history (```HistoryLimit``` is now expressed in minutes)
- Fixed duplicated event raising causing also issues with History/Statistics (#228)
- Added new API command ```/api/HomeAutomation.HomeGenie/Config/Modules.StatisticsGet/<domain>/<address>/<parameter>```
- Added new API command ```/api/HomeAutomation.HomeGenie/Config/Modules.ParameterGet/<domain>/<address>/<parameter>``` (should close issue #206)
- Optimized SSE
