### ISSUE TITLE
Danfoss Thermostats Wake Up communications problems

### ISSUE THREAD

**Issue by bfkmnemonic** [genielabs/HomeGenie#226]
Hi,

I am quite new to both Z-Wave and HomeGenie, and I have been trying to make my thermostats work for the last 3 days without much luck. (Danfoss Living Z Thermostats)

I am able to do the SetPoint, but only if I wake the thermostats manually first, and only if I really time it. Why does it not hold the settings until wakeup and then send the command?

Best Regards

**Comment by genielabs** [comment]
this should be solved with latest hg.

**Comment by bfkmnemonic** [comment]
Thank you for taking the time to fix this. It works great now!
