### ISSUE TITLE
Timetable widget bug

### ISSUE THREAD

**Issue by evanspae** [genielabs/HomeGenie#229]
I am based in the UK where current time of BST is 1hr ahead of BMT. 
In my system the times shown and passed forward as variables in the timetable widget for Lights and Switches appear in the widget gui to be based on GMT even though my system is based on BST. 
In practice therefore to program say a 18:00 (BST) timetable switch, the widget has to set to 17:00 (which is GMT). Obviously this is very confusing!!
The timestamp in the page_events shows the timetable event  correct as in BST, even though the timetable time programmed time was 1hr earlier (ie in GMT). I hope this makes sense.

I would just add that scheduled time events program, display and happen correctly in system time ie BST

**Comment by genielabs** [comment]
Is the timezone correctly set on the machine where HG is running? Btw, time is always stored as UTC in HG.

**Comment by evanspae** [comment]
Yes I should have added HG is running on a Rpi2 and I am scheduling from a Win7 client set to UK ie BST. Confusion is discrepancies between scheduled widget time and actual event/log time

**Comment by genielabs** [comment]
is the Rpi2 timezone also set to BST?

**Comment by evanspae** [comment]
I will check, I have not specifically set. Was a standard wheezy install. Is there a quick cmd check?

**Comment by evanspae** [comment]
The following information has been given:

        Britain (UK)

Therefore TZ='Europe/London' will be used.
Local time is now:      Sat Oct  3 22:18:43 BST 2015.
Universal Time is now:  Sat Oct  3 21:18:43 UTC 2015.
Is the above information OK?
1) Yes
2) No
#? 1

You can make this change permanent for yourself by appending the line
        TZ='Europe/London'; export TZ
to the file '.profile' in your home directory; then log out and log in
again.

I confirmed that RPI2 is set to London time so not change to my original
comments...
Scheduled events work ok on local time page_events also report in local time
With above settings Timetable events programed in widget seem work on UTC,
events_list reports back switch in local time

**Comment by evanspae** [comment]
Now checked and using to select set to 8 Europe and 8 UK

**Comment by evanspae** [comment]
Ok so are we saying that HG can never work on the RPI with local time settings?

Having tried multiple tests it seems that the scheduler and page_events happy work and report in local time, whereas the Timetable widget will only work on UTC even when the RPI has been set to a local time??

**Comment by genielabs** [comment]
I am not sure what are you talking about. What I can say is that if you correctly set the same time zone on both client and server it will work just fine. The only improvements I would see is to make the Timetable widget send UTC values and so the Timetable program accept UTC values. So even if client and server have different time zones it would work. But this is another story that could be marked as ```improvement``` (that I am not personally going to make in the near future :) since usually clients and server belong to the same tz).

**Comment by evanspae** [comment]
I only raised these points because of my unfamiliarity with the system and to ensure others understand the parameters they will be utilsing not to be critical.
The whole project is amazingly comprehensive, now I know which components use UTC and those that  use local time it is certainly very usable.

**Comment by genielabs** [comment]
I wish I had more time to make all of this better, but it's getting to be a huge project for one coder only. I periodically check opened issues, so I will come back on this if no one else contributed in the meantime.

**Comment by evanspae** [comment]
Ok np
