### ISSUE TITLE
Request: Implementation Of ZigBee Communication

### ISSUE THREAD

**Issue by ado464** [genielabs/HomeGenie#23]
Zigbee would be awesome to have in this system since we have a lot of others, like z-wave. I am guessing you are running this as well in C# so i have been searching to find something, anything to do with zigbee and C# if it even helps:

1.https://code.google.com/p/sharpxbee/
2.https://code.google.com/p/smarthus/

cheers, Ado

**Comment by kevin789900** [comment]
FYI... There is a Nortek Zwave & ZigBee combo USB stick available now: http://www.nortekcontrol.com/gocontrol-detail.php?productId=1773

**Comment by sebyno** [comment]
Just discovered this project, actually I'm using Domoticz.
For zigbee this may be interesting:
https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html
https://gadget-freakz.com/diy-zigbee-gateway/

**Comment by genemars** [comment]
I'm closing this since ZigBee is now supported by HG.
