### ISSUE TITLE
MIG.Gateways Windows authentication problem

### ISSUE THREAD

**Issue by djidrov** [genielabs/HomeGenie#230]
Upgrading my HomeGenie instance I realized that when authentication is set up Gateway is frozen.
This is the first time I look up into source of home genie and I found an error in MIG.Gateways WebServiceGateway.cs

the code change is **bold**, from line 576:
                    {
                        response.StatusCode = (int)HttpStatusCode.Unauthorized;
                        **//response.Headers.Set(HttpResponseHeader.WwwAuthenticate, "Basic");**
                        **response.AddHeader("WWW-Authenticate", "Basic");**
                    }
                }
                else
                {
                    response.StatusCode = (int)HttpStatusCode.Unauthorized;
                    **//response.Headers.Set(HttpResponseHeader.WwwAuthenticate, "Basic");**
                    **response.AddHeader("WWW-Authenticate", "Basic");**
                }

error was that WWW-Authenticate header does not exist.

I hope that this will be included in next version.

**Comment by genielabs** [comment]
what do you mean by saying that WWW-Authenticate header does not exist?

```response.Headers.Set(HttpResponseHeader.WwwAuthenticate, "Basic");```
doesn't work under windows?

**Comment by djidrov** [comment]
On windows does not work. With presented change does work.

Sent from my Windows Phone
________________________________

**Comment by genielabs** [comment]
Ok... I applied your fix, it will be available along next update.
