### ISSUE TITLE
Homegenie Plus - Feature requests

### ISSUE THREAD

**Issue by pim555** [genielabs/HomeGenie#232]
Have installed Homegenie Plus after using Homegenie Android the the last year. Like it a lot, also as pure mobile app. Couple of features I would think add further value:

- option to enable vibrate in the preferences menu to allow the device to vibrate shortly when selecting the switch/lamp/etc. to switch on or off. This helps in confirming the user that the button was actually pressed.
- option to customize the colors/styling of the UI. Personally I like the style (fonts, colors) of the standard Android app better. I guess that is quite subjective and as such it would be great if one could select a template.
- I run the app on a Galaxy s6 and for me, the widgets might even fold down smaller. I can see in some screenshots that multiple widgets sit on the same horizontal row but I dont see that on my phone. I am not sure what defines the layout but either having more control on that or an option to further fold down the widgets would be great.
 
Pim.

**Comment by genielabs** [comment]
issue tracker for hg plus moved here:
https://github.com/genielabs/homegenie-plus-android/issues
- vibrate option is now available in the preference
- theming will be done at some point
- number of rows depends on device screen density
