### ISSUE TITLE
email fails to communicate with SMTP server

### ISSUE THREAD

**Issue by bkenobi** [genielabs/HomeGenie#25]
Neither Yahoo nor gmail appear to work as a valid smtp servers within HG.  I can manually send a message from my RasPi using openssl, so I know my system and inputs are correct.  From reading various sites, it looks like the issue is caused by servers running ssl on port 465 when .NET is used.  There is a workaround specified in the following stackoverflow post:

http://stackoverflow.com/questions/1011245/how-can-i-send-emails-through-ssl-smtp-with-the-net-framework

Details of my tests are at:

http://www.homegenie.it/forum/index.php?topic=320

**Comment by nvuono** [comment]
Found the solution to this for gmail and a similar solution probably works for yahoo if you change the URL used in the commands they use at http://www.mono-project.com/docs/faq/security/ under the heading for the question "Does SSL work for SMTP, like GMail ?" specifically related to adding the root certs under the MACHINE account and then importing the intermediate certificates:


     mozroots --import --ask-remove --machine
     certmgr -ssl smtps://smtp.gmail.com:465

**Comment by bkenobi** [comment]
Looks like mozroots isn't installed on the HG RPi image.  I'll update my backup and try installing mozroots so I can try this.
