### ISSUE TITLE
Earth Tools Program has incorrect link.

### ISSUE THREAD

**Issue by fredsterp** [genielabs/HomeGenie#253]
The URL within the program is incorrect...there is a new web address.

Line 11 is - "http://www.earthtools.org/sun/"
Line 11 needs to be - ""http://new.earthtools.org/sun/"

**Comment by genielabs** [comment]
Thanks, fixed it. Starting from r513, packages-related issues have to be submitted here:

https://github.com/genielabs/homegenie-packages

Are you already using r513?

**Comment by fredsterp** [comment]
Great...thanks!

Using v1.1 r512 right now, but will update.

Recommend placing a link to the git packages repository on the main HomeGenie git page.
