### ISSUE TITLE
reusing deleted PID codes

### ISSUE THREAD

**Issue by storm1988** [genielabs/HomeGenie#258]
The problem is explained on the forum linked below.

http://www.homegenie.it/forum/index.php?topic=1446.0

The short description is when an old PID number that was on a program that is then deleted, A new  program will then use the old free PID but then the second new program will use the same PID again.

**Comment by genielabs** [comment]
fixed https://github.com/genielabs/HomeGenie/commit/eb52731fd6b19a0febe82a084719964c49d3fc2f
