### ISSUE TITLE
Cant create any new programs.

### ISSUE THREAD

**Issue by kevinvinv** [genielabs/HomeGenie#259]
When one tries to create a new C# program,  The new program ends up being an old program instead...  rendering it impossible to create a new fresh program.

This is discussed here:
http://www.homegenie.it/forum/index.php?topic=1455.0

Thanks!

**Comment by genielabs** [comment]
fixed https://github.com/genielabs/HomeGenie/commit/eb52731fd6b19a0febe82a084719964c49d3fc2f
