### ISSUE TITLE
"The package is of bad quality" while installing homegenie-beta_1.1.r514_all.deb on Ubuntu 15.10

### ISSUE THREAD

**Issue by davidrivers** [genielabs/HomeGenie#263]
As linked from the website, trying to install http://netcologne.dl.sourceforge.net/project/homegenie/homegenie-beta_1.1.r514_all.deb on Ubuntu 15.10 (by launching it and allowing Ubuntu Software Center to install it) provokes a Lintian check which fails with [the following error messaging](https://gist.githubusercontent.com/davidrivers/8f6f94f98e02383f3e81/raw/5b5c96ec6640e5bbadc98f5a2b1e2cecad8ff667/gistfile1.txt).

![screenshot from 2016-03-17 19-52-25](https://cloud.githubusercontent.com/assets/33893/13864658/dcf6f908-ec79-11e5-8cfe-65a0ebadb714.png)

...And now I have a sad because I really want to use this software, but I'm wary of installing it after failing the Lintian checks :( I also tried the previous release (homegenie-beta_1.1.r512_all.deb) and unfortunately encountered the same roadblock.

**Comment by genielabs** [comment]
use **gdebi** for installing homegenie. Read instructions here: http://genielabs.github.io/HomeGenie/install.html
