### ISSUE TITLE
Tamper displayed on widgets under normal behavior. 

### ISSUE THREAD

**Issue by wolfer201** [genielabs/HomeGenie#270]
I purchased several door and window sensors. Im not sure the reasoning but under normal behavior they send a 0xFF to Sensor.Alarm permanently. The manual even confirms this. 

For example an from my motion sensor manual:

> When the sensor detects motion, it will send a status of “ON” (Basic Set,
> Value: 0xFF) and alarm report (Type: 07, Level: 0xFF) to any associated
> nodes. The red LED will flash once.

The problem is the door sensor, motion sensor widget and Security alarm log display this as a tamper alert. I was able to hide this just by editing some lines in the widgets to only look for sensor.tamper and ignore sensor sensor.alarm but that doesn't help the big red letters in HG+. 

![screenshot_2016-04-11-20-27-32](https://cloud.githubusercontent.com/assets/18411532/14449074/3f257236-0024-11e6-9395-6ab1e9746428.png)

It would be nice is there was a way to toggle off which values are displayed. I could care less about sensor.alarm, especially sensor.tamper reports the true tamper.

**Comment by genielabs** [comment]
Added in HomeGenie Plus r28 (just published on Google Play Store).
