### ISSUE TITLE
Scheduler Issues

### ISSUE THREAD

**Issue by TasioX** [genielabs/HomeGenie#271]
since upgrade from 512 to 515

2016-04-12 09:30:33.4221 Info HomeAutomation.HomeGenie   Scheduler   @SolarAltitude.Evening.GoldenHour.Start   Scheduler.Error   "Too much recursion in expression '@SolarAltitude.Evening.GoldenHour.Start'"

This is happening with several other scheduled events most are JKUtils schedules but at least one is a custom schedule.

This happens with multiple different scheduled events including custom and built in schedules.  Including @Sunset and so on.  This disables the event and prevents the scripts from running.  Almost all scheduled scripts will not trigger.  This can be duplicated in Windows and RPI.  If I assign a script to a different schedule it generally also causes the newly chosen event to fail.  I even rebuild my HG from scratch and it still happens.  I know others are also having similar issues.

All of my scheduled scripts are built using the Wizard Script

**Comment by genielabs** [comment]
I did a quick test and could not reproduce the issue. 
I tried just "@Sunset" in a wizard script. Are you using a composite expression?

**Comment by TasioX** [comment]
![scheduler](https://cloud.githubusercontent.com/assets/18470702/14589850/9d74b912-04a9-11e6-9e90-ba1048bd2b9b.jpg)

**Comment by TasioX** [comment]
![scheduler](https://cloud.githubusercontent.com/assets/18470702/14589857/c4b1b87c-04a9-11e6-9c1b-afea5b6218e4.jpg)

**Comment by TasioX** [comment]
![image](https://cloud.githubusercontent.com/assets/18470702/14589865/f1073028-04a9-11e6-8289-e3553c6d919b.png)

**Comment by TasioX** [comment]
![image](https://cloud.githubusercontent.com/assets/18470702/14589869/ffd65764-04a9-11e6-94d4-47dfef23ee8a.png)

**Comment by TasioX** [comment]
The first image is the result once a script is scheduled.  The second is the schedule in the script.  The third is the program to run.  Pretty standard script.  No frills.  "@ChronEvent" run "Philips Hue Light X" "Control on".  Has worked without issue for the past year or so.  I have several similar scripts that cause the same issue which is why you see multiple schedules disabled in image 1.  Generally about 1 out of 5 scheduled scripts will run.  Seem to sometimes change which will run if you reboot.

**Comment by TasioX** [comment]
Here is the event log pulled right after I did a restart on Solar Altitudes


![image](https://cloud.githubusercontent.com/assets/18470702/14589956/f40c477a-04ab-11e6-84dd-304599f67a0b.png)

**Comment by TasioX** [comment]
Gene,
I just confirmed duplication on my system.  I previously was not actually using @Sunset for any triggers.  I created a new script to trigger @Sunset and turn on 2 lights.  I restarted HG and @Sunset was disabled along with several of the same Solar Altitudes schedules.  I did see a bit a variance in which schedules became disabled but it is clearly linked to the scripts calling on them in some way.

**Comment by genielabs** [comment]
I just pushed a fix to the **IsScheduling** method. Not sure if it will solve this issue. You can test either by building from source or using the prebuilt patched r516 package uploaded here:
https://sourceforge.net/projects/homegenie/files/testing/

**Comment by TasioX** [comment]
Gene,
So far so good.  Had to re-enable the disabled schedules after restore from backup but then they seemed to stick.  Restarted the service, and restarted JKUtils and everything seems to be holding.  Let me know if you drop a windows build of this as the machine I usually run on is Windows based.  Sorry I don't do much coding so building from source is a challenge.
Thanks for digging into this.

**Comment by TasioX** [comment]
Just noticed that this build may have fixed my chrome issues from my other bug report also.  I would need a windows version to test to be sure.

**Comment by TasioX** [comment]
In 517 this appears completely fixed.

Thanks Gene!
