### ISSUE TITLE
Chrome fails to completely load all pages

### ISSUE THREAD

**Issue by TasioX** [genielabs/HomeGenie#272]
Chrome intermittently fails to load all pages.  Widgets do not appear and the browser never finishes loading the page no matter how long you wait.  Pages will fail to load until you close and reopen browser and sometimes until you restart HG.  

Problem do not happen with IE

Had this same issue at one point with on of the 1.0 releases but do not recall which release it was.

**Comment by rogerjak** [comment]
Same for me, also in FF, didn't help with the improved caching in 516 :(

**Comment by TasioX** [comment]
I have had mixed results with 516 and chrome.  I did eventually get it to respond.

**Comment by pcguru** [comment]
I have the same issue when running from master on my development machine. Running 516 on my very slow windows server works perfectly fine.

Could we be running into som e kind of rate limit in the webserver? I'm clueless as to why the webserver just chokes. If you stop the load in chrome, then the webserver registers the requests for a bunch of images that failed to load in chrome. But not until you stop loading in Chrome. Looks weird in the network tab of developer tools.

**Comment by TasioX** [comment]
This continues for me in 517.  Mine is the opposite, Windows server will not work on some machines but my RPI works fine.

**Comment by genielabs** [comment]
please try on r521

**Comment by pcguru** [comment]
Looks good to me. Load is slow the very first time after a restart of HG, but after that, even with cleared cache, the load always work.

**Comment by TasioX** [comment]
I still seem to be having this issue on my windows server machine.  The behavior has improved but I often have to hit the back button and then hit forward again to get the page to continue to load.

**Comment by rogerjak** [comment]
Better, but still a problem, mostly FF and Vivaldi, but also Chrome and IE.

**Comment by noliono** [comment]
I have this bug too, to avoid it, i go to "statistics" and come back to "home".
