### ISSUE TITLE
Zwave and Light Module "Feature" changes do not stick

### ISSUE THREAD

**Issue by TasioX** [genielabs/HomeGenie#275]
When I open a widget module in either Zwave and Lights and try to change the feature/option to a different feature the change does not stick.  This happens in both IE and Chrome on both RPI and Windows.  I know that it has been happening at least since version 512 but is present all the way up to 517.

EX: Changing a light from "Energy Saving Mode" too "Level Memory" when reopened the widget will have reverted back to the first item in the list.  In my case "Energy Saving Mode" is the first option in the list.

![image](https://cloud.githubusercontent.com/assets/18470702/14938152/32c91ade-0ed8-11e6-9606-7cc3b5d87230.png)

This is the event log pull.

![image](https://cloud.githubusercontent.com/assets/18470702/14938188/295d58ba-0ed9-11e6-896e-3a27e4d1046e.png)

Thanks,

Tasio

**Comment by genielabs** [comment]
Hi can you please try r519 and report?
https://sourceforge.net/projects/homegenie/files/?source=navbar

**Comment by TasioX** [comment]
Tested RPI and Windows, IE and Chrome.  Still not reflecting changes made to the features.

**Comment by genielabs** [comment]
"EX: Changing a light from "Energy Saving Mode" too "Level Memory" when reopened the widget will have reverted back to the first item in the list. In my case "Energy Saving Mode" is the first option in the list."

wait a minute...this has always been like this. When you select a feature set then it will display all flags and options for that particular feature (e.g. energy saving mode). You're not enabling anything by just changing the feature set in the select menu, but you do when you set various options shown below the select menu of each feature and so by clicking "Save" button to make changes effective.
