### ISSUE TITLE
Homegenie Update Manager Fail

### ISSUE THREAD

**Issue by daberk** [genielabs/HomeGenie#281]
In HomeGenie Version 1.1 r525 running on a Raspberry PI the update checker fails with an Error.

**Comment by K2DLS** [comment]
Update install fails on r519 also.  The installation file cannot be downloaded because it is not found.  Error is "Error while downloading update files."

**Comment by Bounz** [comment]
Hi, @K2DLS.
Perhaps you need to update certificates on your RPi.
See this message on community forum: http://www.homegenie.it/forum/index.php?topic=129.825

**Comment by K2DLS** [comment]
Not currently running on an RPI but via Debian on x86_64, but anyway:
mozroots --import --ask-remove --machine
Mozilla Roots Importer - version 3.2.8.0
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell.
BSD licensed.
Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/
lib/ckfw/builtins/certdata.txt?raw=1'...
Couldn't retrieve the file using the supplied information.
This after installing mono-devel and mono-complete!

**Comment by K2DLS** [comment]
This imported 90+ certificates...
mozroots --import --sync --machine --url "http://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt"

I get a "Connection error!" when I try to run the update check (now on r525).
