### ISSUE TITLE
Modbus TCP IP

### ISSUE THREAD

**Issue by amicum123** [genielabs/HomeGenie#291]
Hi, I have found HomeGenie very flexible and possible very usefull SCADA system for my projetcs. Every thing is simple and easy to use, but something is missing. Every thing I made from scratch (based on ATMega MCU's and others) is connected to ModBus TCP/IP. Looking from other prespective, this protocol is one of the most used in automatition today and probably I'm not the first one with this request.
It will be realy cool if HomeGenie will support this protocol, it will open doors to may new possibilites and new devices, DIY and commercial to connect to this amazing software. 
This is pure request to implement this protocol and make HomeGenie more wider and open for new things, that just wait for implemetn.

**Comment by ajaywazir** [comment]
Hi
Any response?
Ajay

**Comment by Bounz** [comment]
Hi.
I think that it may be implemented only by somebody having such devices. But it looks they are not very common in home automation though.
If you can implement this protocol in form of MIG interface - that would be great!
