### ISSUE TITLE
postinst: sudo: not found

### ISSUE THREAD

**Issue by hutorny** [genielabs/HomeGenie#299]
`/var/lib/dpkg/info/homegenie.postinst: 2: /var/lib/dpkg/info/homegenie.postinst: sudo: not found`
...
`/var/lib/dpkg/info/homegenie.postinst: 9: /var/lib/dpkg/info/homegenie.postinst: sudo: not found`

I guess sudo should be listed among dependencies or there should be an option doing it without sudo

**Comment by genielabs** [comment]
which s.o. ?
