### ISSUE TITLE
X10 not functioning correctly with multiple UC sent before command

### ISSUE THREAD

**Issue by bkenobi** [genielabs/HomeGenie#30]
As reported here:
http://www.homegenie.it/forum/index.php?topic=360.0

If multiple unit codes are sent in a row prior to an action command, HG only processes the last UC.  HG should process all UC on the same HC with the command on that unit code.

Example:
A2, A3, A4, A ON

Result:
modules on A2, A3, and A4 should all be turned on

HG response:
modules on A4 are turned on

**Comment by bkenobi** [comment]
Just curious if this is still being looked at or if I can provide any debug help?

**Comment by genielabs** [comment]
see attacched files here:
http://www.homegenie.it/forum/index.php?topic=579.msg3672#msg3672
g.
