### ISSUE TITLE
Temperature units are not consistent

### ISSUE THREAD

**Issue by hutorny** [genielabs/HomeGenie#301]
In some places temperature is always in Fahrenheit, in some others - in Celsius.

![hg-temp-units](https://cloud.githubusercontent.com/assets/2145885/20940968/3d8f48b2-bbfd-11e6-8354-676f09fa0cf0.png)

**Comment by genielabs** [comment]
The data in the weather widget is static (fake) unless you configure it. You've to configre it and will display the right units.
