### ISSUE TITLE
Feature Request!!

### ISSUE THREAD

**Issue by davidwallis3101** [genielabs/HomeGenie#311]
I would try testing this myself, but the javascript side of homegenie is erm.. well scary :)

I was using .net fiddle and noticed intellisense / autocomplete and thought hmmm, quick google suggests its Roslyn doing that... so a further google returns: 

https://github.com/ashmind/mirrorsharp

Could be interesting and make dev a whole load easier!

**Comment by Bounz** [comment]
There is a problem, that HG is built on top of its own web server inside MIG library, not on ASP.Net, that is required to use mirrorsharp.
Right now it's only possible to use CodeMirror show-hint addon to add some code completion. See https://codemirror.net/doc/manual.html#addon_show-hint.

**Comment by davidwallis3101** [comment]
I do wonder if there is any benefit moving to owin and remove that part of
the code base?

**Comment by Bounz** [comment]
Right now "web server" is just another interface inside MIG library along with X10, Z-Wave and others. It looks not so easy to decouple them.
I thought about this but decided to leave it as is and try to create new UI on top of Vue.js and write some unit-tests on ZWaveLib using public documentation.

**Comment by davidwallis3101** [comment]
sounds interesting!

On 16 Mar 2017 19:55, "Alexander Sidorenko" <notifications@github.com>
wrote:

Right now "web server" is just another interface inside MIG library along
with X10, Z-Wave and others. It looks not so easy to decouple them.
I thought about this but decided to leave it as is and try to create new UI
on top of Vue.js and write some unit-tests on ZWaveLib using public
documentation.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/genielabs/HomeGenie/issues/311#issuecomment-287172775>,
or mute the thread

**Comment by davidwallis3101** [comment]
In the short term I looked to see what the CSharpAppFactory was doing and created a vs project that mimics what is compiled for a program DLL - I May test to see if I can work out a way of importing something created outside of HG - maybe using a vs code task runner task and the HG api, or a Post build activity..

But in the mean time this lets me get autocomplete and re-sharper support for the mig methods etc as a quick win :) which I can then paste back into the code editor.

**Comment by davidwallis3101** [comment]
closed by accident as I would still like Gene's thoughts :)
