### ISSUE TITLE
Homegenie forum not accessible

### ISSUE THREAD

**Issue by jamesthomas128** [genielabs/HomeGenie#324]
What has happened to the HG forum?  I just get redirected to the HG info pages when trying to access it.

**Comment by Bounz** [comment]
Hi @jamesthomas128.
The old HomeGenie forum had has been closed and the community has moved to https://homegenie.club.

**Comment by tuicemen** [comment]
For those using X10 there is always the X10 forum for HG help ! Http://forums.x10.com 
It is also where you'll find a Pi image which includes HG pre-installed.

**Comment by noliono** [comment]
> Hi @jamesthomas128.
> The old HomeGenie forum had has been closed and the community has moved to https://homegenie.club.

@jamesthomas128 Can you close this issue?
