### ISSUE TITLE
Scheduler event doesn't show up if date period spans years

### ISSUE THREAD

**Issue by llamontjr** [genielabs/HomeGenie#325]
Trying to add a scheduler event that spans for example, Nov25th -> Jan 8th, does not show up in the active schedules even though today is Dec 10th.  If I change the date period to Nov25th -> Dec 31st, then all shows up properly.  

This just seems to have started in the 1.1-526 release.  It was working in 525.

**Comment by genemars** [comment]
This is a bug.
As a work-around you can add two scheduler events. The first up to december 31st and the second from january 1st to the desired end date.

**Comment by nickpbd** [comment]
Did this get fixed? I gave it a try as my "first issue" and I can't recreate. I scheduled a date period Dec 28 to Jan 2 and it shows on Dec 29th calendar view

**Comment by genemars** [comment]
I'll take care of this for the next release.

**Comment by nickpbd** [comment]
I was checking if it was already fixed. I wanted to fix it myself but i can't recreate the problem
