### ISSUE TITLE
Can we use the HG manual updater to revert to a previous build?

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#338]
I've been testing the latest beta builds but these have rendered many of my wizard created programs inoperable. Is it possible to use the manual updater in HG to revert back to a build that was stable for my situation?

If not may be this can be added as a option at least while beta builds are installed.
It sure would save time and may lead to others testing beta builds.

**Comment by genemars** [comment]
Latest build (1.2-beta.8) should solve the issues with wizard scripts. Can you confirm?

**Comment by tuicemen** [comment]
Just noticed in the user created programs there is an error icon on the right which appears in both the program code and trigger code tabs.
clicking on this displays "Object reference not set to an instance of an object"

**Comment by genemars** [comment]
If this is a c# user program, compiling/saving it might solve the issue.

**Comment by tuicemen** [comment]
@mralapete I've reverted back to 1.1-stable.527 to get a working system.
Since this was an update starting from 1.2.beta.2 I suspect it was the same unless the updates changed that.
mono 4.2.6(Debian 4.2.6.2+dfsg-1)
I'll attempt a fresh install on a new SD card and see if that fixes it. 
@genemars these were C# programs a reinstall of them still left out the start up code so I'd need to manually add all that info prior to compiling/saving I suspect but will try once I get a new SD image and HG installed on it.

**Comment by tuicemen** [comment]
Ok done a fresh install (not a update) of 1.2-beta.8
The Programs come up with an error when I open to edit however the start up code displays. so the updater is blocking or missing something.
Clicking save HG reports an error something about format  (script, script, script)  no longer supported, says to use something instead but I can't read the whole message prior to it closing.
However after saving the error disappears and I can run these programs.

I'm not sure a revert to previous build would have helped here as the issue may have followed the revert unless HG just ran a uninstall then install script. But that may have been your idea for this any ways @genemars .

**Comment by tuicemen** [comment]
I created a script to revert to a specific HG build which actually works very well for the X10 community created PiX10Hub Image as a work arround for now.
