### ISSUE TITLE
System.TypeInitializationException on Windows due to referencing old nlog in app.config

### ISSUE THREAD

**Issue by nickpbd** [genielabs/HomeGenie#340]
### Expected behavior
The service starts

### Actual behavior
Service fails in the static initialization of nlog when calling HomeGenieService constructor:
FileLoadException: Could not load file or assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### Steps to reproduce the problem starting from a fresh install

  1. Install Windows version
  2. Run
  3.

### Specifications

  - Version: 1.1-stable.527
  - Operating System:  W10 & Server 2008
  - .Net/Mono runtime version:
  - Hardware configuration: 

#### Additional configuration notes

Caused by the dependentAssembly entry in app.config referencing 0.0.0.0-4.0.0.0 or 4.1.0.0 when the version in use is 4.5.10.
Removing the config below resolves the issue:
            <dependentAssembly>
                <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
                <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.1.0.0" />
            </dependentAssembly> 

alternatively newVersion="4.5.10"

**Comment by genemars** [comment]
thanks for reporting =)
