### ISSUE TITLE
1.2 beta-16 broke my hue modified program

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#344]
I created a program which simply modified the Philps hue program to allow connection to the HA-Bridge program since I don't have a physical Hue Bridge and to provide the ability to arm disarm my X10 security system this was working fine until the latest beta release
### Expected behavior
Ha-Bridge configured devices to turn on/off when called to do so

### Actual behavior
HG shows the command is being sent via a toast message but nothing gets activated

### Steps to reproduce the problem starting from a fresh install

  1.
  2.
  3.

### Specifications
 - Version: 1.2-beta-16
  - Operating System: Raspbian stretch
  - .Net/Mono runtime version: Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1)
  - Hardware configuration: pi 3b+ & zero W  

#### Additional configuration notes
I also have the email camera pictures which had stopped sending prior.
 I'm wondering if this is all related to the mono version as reported in issue #342 
I've not updated mono to the latest as yet as I figured HG would do that with an update.

**Comment by genemars** [comment]
Can you post the `.hgx` of this program with steps to replicate the issue?

**Comment by genemars** [comment]
Did you clone the hue program or did you modify the code of the original program?
In the latter case the original program might have been overwritten with the hg update.

**Comment by tuicemen** [comment]
sorry for the delay just got back and trying to get caught up here is the hgx file

[260-HA-Bridge(with Password).zip](https://github.com/genielabs/HomeGenie/files/2601542/260-HA-Bridge.with.Password.zip)

**Comment by tuicemen** [comment]
Ok I'll give this ago and see what happens with a new HG beta release.
I had assumed if I imported my modified program with the original still in place HG would assign a new id.
not sure why other releases didn't catch this.

**Comment by tuicemen** [comment]
Perhaps the built in Hue Hub program can be updated to include  a password then my HA-Bridge (modified hue program) would be obsolete.

**Comment by tuicemen** [comment]
I believe that this is no longer a issue as every thing seems to be working!
