### ISSUE TITLE
CM19a not working

### ISSUE THREAD

**Issue by alzzy** [genielabs/HomeGenie#349]
I installed latest release on win 10 Laptop and it would not control a cm19a. Enabled cm19 interface but it does not respond. PC recognizes cm19 and driver is working. After I had this issue I installed x10 Commander and it controls devices with cm19a just fine. Did a reinstall of HG and got same results.

**Comment by mralapete** [comment]
Is there any other X10 software installed on your computer.

**Comment by alzzy** [comment]
No.

**Comment by tuicemen** [comment]
x10 commander uses X10 drivers so these would conflict with HG have you tried another USB port?

**Comment by alzzy** [comment]
x10 commander was not on pc initially. I only installed it after HG would
not control cm19. To verify pc would communicate with cm19 and that cm19
was ok. Besides cm19 is a usb device and any app should be able to get to
it. Removed x10 commander and still had issue.

**Comment by alzzy** [comment]
Yes tried all 3 usb ports.

**Comment by alzzy** [comment]
Tried to install HG on a second Win10 machine. Get popup window says "7-zip error unsupported method"
Installed but when I go to config screen there is nothing there .

**Comment by tuicemen** [comment]
May be try a different free zip tool from the Windows store

**Comment by tuicemen** [comment]
Gene has put out a couple releases since your post. I'm not sure which version you tried but you may wish to try stable22 as many of the prior releases are now labled prereleases and some aren't even available now.

**Comment by alzzy** [comment]
where do I find it? The HG download page is throwing a 404 error.

**Comment by tuicemen** [comment]
https://github.com/genielabs/HomeGenie/releases/tag/v1.2-stable.22

**Comment by tuicemen** [comment]
If you wish to use the same version as the PiX10Hub then this https://github.com/genielabs/HomeGenie/releases/tag/v1.1-stable.527

**Comment by alzzy** [comment]
Which file do I want for windows install?

**Comment by tuicemen** [comment]
When in doubt check the documentation https://genielabs.github.io/HomeGenie/index.html#/get_started for the latest versions.

However the EXE extension  one should get you the Windows version

**Comment by alzzy** [comment]
Already tried that. That webpage is not at all helpful for this install as it directs one to a windows install page that goes to a 404 error page. I tried the .exe file from the github Unzipped with win zip. But there is no msi installer. Once unzipped what file does the actual install?

**Comment by genemars** [comment]
@alzzy can you please try latest build?
https://github.com/genielabs/HomeGenie/releases/tag/v1.2-stable.26
Is there someone that can also test this with a CM15 on Windows?

**Comment by mralapete** [comment]
I assume you installed the driver first and rebooted your PC before you connected the CM19

**Comment by tuicemen** [comment]
@genemars I can test this but not till the week end.

**Comment by alzzy** [comment]
Can someone direct me to details on how to install this in windows?

Thanks

**Comment by tuicemen** [comment]
I would assume download this- https://github.com/genielabs/HomeGenie/releases/download/v1.2-stable.26/HomeGenie_v1.2-stable.26.exe 
then click on the exe file

**Comment by alzzy** [comment]
OK Thanks I will try later today. Is there any special procedure for installing drivers or are they installed automatically with the application?

**Comment by mralapete** [comment]
Windows installer should take care of everything. Remember no other X10 drivers should be installed as they will cause a conflict. After install check your Windows device driver. You should see it loaded there.Install first then connect the CM15

**Comment by alzzy** [comment]
It WORKS! v1.2-stable26 installed on win 10 and controls cm19a. Will do more testing later.
Thanks for the help!

**Comment by tuicemen** [comment]
@alzzy  that's Great!
 Maybe you can close this issue. and if after testing you find a problem then a new issue can be opened.Iit helps keep things tidy and nothing gets missed.
