### ISSUE TITLE
Option screens for programs don't load

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#351]
### Actual behavior
now when you select a program the edit page pops up with no chance to add/enter option info

### Steps to reproduce the problem starting from a fresh install

  1.once installed click on options
  2.click weather and environment.
  3.click on weather underground which will take you directly into edit.
I only use the weather underground program as an example the same happens for any program.

### Specifications

  - Version: 1.2-stable.27 
  - Operating System: Raspbian stretch lite
  - .Net/Mono runtime version: mono 5.6
  - Hardware configuration: Pi Zero W

#### Additional configuration notes
I first noticed in version 1.2-stable.26 when I went to update the Camera program with new configuration info for a camera
I did a factory reset thinking it may be my backup that had got corrupt  but that's not the case.
 the issue isn't present in 1.2-stable.19

**Comment by tuicemen** [comment]
It is looking more like  bad backup files :(
have same issue on mono 4.62 even if I revert to HG 1.2-stable.18
I'd do some more testing  looks Like I introduced something HG doesn't like with a back up maybe an addon program

**Comment by genemars** [comment]
Hi @tuicemen,
the program options popup has been removed from the program's list page. Now clicking on a program from the list will open the editor.
Program's options are still available from the **Configure->Settings** page.

**Comment by tuicemen** [comment]
@genemars  Ah no wonder I couldn't figure out what the cause was thought it was my back up but I loaded it in an older version and it worked till updating. thanks for the Heads up that saves me a day  of useless trouble shooting.
