### ISSUE TITLE
Raspberry Pi CSI camera module not working with HG in Raspbian Stretch

### ISSUE THREAD

**Issue by mralapete** [genielabs/HomeGenie#352]
@genemars Back with HG v519 and Raspbian Wheezy HG recognised the Raspberry Pi CSI camera module and was able to display an image. The support for this I believe was done through the v4l2 driver package. This stopped working in Raspbian Jessie and still does not work in Raspbian Stretch.

Would it be difficult to reintroduce support in HG for the Raspberry Pi CSI camera module.

**Comment by genemars** [comment]
I think that the best option is to install some other specific software (eg. **picamera**) and then use the *Generic IP Camera* program to integrate it in HG.

**Comment by mralapete** [comment]
@genemars I still have the HG Raspbian Wheezy setup with the CSI camera moduke working on the Raspberry Pi. I'll look into the v4l2 driver that's setup for it. I imagine I'll be able to replicate this in Raspbian Stretch by rebuilding a newer version of the bcm2835-v4l2 driver and modprobe it into my current install. I did a bit of work on this in Raspbian Jessie but didn't have the time to finish it off. Just need to get it recognised as /dev/video0 in HG.

As this is a query relevant to the Raspberry Pi and the Pi has an empty CSI slot going to waste and of course it has previously been supported by HG it shouldn't pose a major problem for me to get this working.

I'll let you know how I progress with thus. Thanks.
