### ISSUE TITLE
Virtual UPnP devices: WeMo emulation tests for Amazon Alexa/Google Home integration

### ISSUE THREAD

**Issue by genemars** [genielabs/HomeGenie#355]
Continuing from thread from #353 .

**Comment by genemars** [comment]
@mralapete can you describe the procedure to add a device to Alexa? This might helping me figuring out what to do.

**Comment by mralapete** [comment]
Also this is where it was left before the old forum was closed down http://old.homegenie.club:8080/www.homegenie.it/forum/index2513.html?topic=1715.0

**Comment by genemars** [comment]
Ok @tuicemen I've got a better HGX to test.
This one adds the **UPnP Emulator** option to the *Options/Features* dropdown of any switch or light module.
Simply activate this flag for every switch and light that you want HG to make discoverable as stand-alone UPnP device (a fake Belkin WeMo type).

[1000-UPnP_Emulator_v1r1.hgx.txt](https://github.com/genielabs/HomeGenie/files/2729697/1000-UPnP_Emulator_v1r1.hgx.txt)
---

**Comment by tuicemen** [comment]
@genemars 
ok this is causeing my brain to go back into a fog I started the program added a couple of devices and selected the alexa option when I attempted to add the alexa option to the second device the option wasn't there so I figured I'd just discover devices with Alexa nothing new was found so I went back to HG and the program wasn't activated so I reactivated it went to be sure the device I'd selected prior was alexa enabled and it wasn't so tried to check that option and it is no longer available

**Comment by tuicemen** [comment]
ok maybe My brain is still not fog free!
Nope I'm sure it isn't now! missing all kinds of stuff that a 4 year old would have done.
I've still not got Alexa to discover anything new  but may be by days end things will start to comeback to me.
So as  of right now don't take my findings to serious. ;)

**Comment by genemars** [comment]
I've integrated this functionality in the new **v1.2-stable.33** release.
Open HG, open a module options (eg. the "Porch Light" in the demo dashboard) and then from the "features/options" list select "UPnP Emulation". Activate the "Emulate UPnP device" option and save.

**Comment by tuicemen** [comment]
Downloading now! is the 1000-UPnP_Emulator_v1r1.hgx still required? should I delete it?

**Comment by genemars** [comment]
@tuicemen you can delete it since it's already present in r33 (under *Devices and Things* category).

**Comment by tuicemen** [comment]
Ok updated changed one of my Zwave switches to emulate UPnP saved the info then opened my Alexa app to discover devices and still no new devices are seen am I missing a step?
Is there a specific switch or light type this has to be applied to?

**Comment by tuicemen** [comment]
My HG is running on Port 8080 should it be on 80?

**Comment by tuicemen** [comment]
well that wasn't any help oh wait my UPnP isn't enabled,....
Well that (enabling didn't help)  Maybe a reboot?

**Comment by genemars** [comment]
@tuicemen UPnP will work despite the port being used for the UI. I also tried Alexa app and it cannot find a thing not even my Hue Bridge, nor the Smart TV.
Maybe using a Echo device gives a better result?
Have you in any case succeed in using the Alexa app with something?

**Comment by tuicemen** [comment]
The Alexa app works and sees HA-Bridge configured devices and Broadlink RM devices.
I also use the PC app https://alexa.amazon.com/spa/index.html#cards which works for discovering but doesn't have the options the phone app has.
I also tried just asking alexa to discover devices with the same result.

**Comment by genemars** [comment]
@tuicemen no need to enable UPnP interface to use this feature.
Anyway to verify that the UPnP devices are created you can use a tool like `gupnp-universal-cp` for linux (part of `gupnp-tools`).
Ok so I'll have a look at how to make it working with HA bridge and I'll figure out eventually what to do.

**Comment by tuicemen** [comment]
you might want to look at  https://github.com/davidwallis3101/HomegenieEchoBridge Too which @mralapete  pointed to earlier.
I had originaly thought of using it for Alexa but the bridge hand support for the Broadlink which allowed capturing and sending any IR or RF signal which enabled X10 security arming and disarming possible.
davidwallis stated it was compile basically the same as HA-Bridge.

**Comment by genemars** [comment]
Ok @tuicemen I had a brief look at the HomegenieEchoBridge code and I think it has a similar approach and, correct me if I am wrong, this require a real Echo device connected to the local network.
So maybe the new HG UPnP emulation will already work with a real Echo/Home device.
If so I don't care about making it work with the Alexa app since this require the user to register or put everything in the cloud. There isn't a single Alexa Skill that do not require the user to register to some sort of cloud service.

**Comment by tuicemen** [comment]
I do not have hubs, just a couple of Amazon Dots  and a Google Home mini  which are connected to my wifi.
the Alexa App needs to see the devices so the amazon devices can activate them.
I can turn on /off X10 lights in the Alexa App or  an Alexa Dot no extra skills required.
if your looking at turning HG into an Alexa or Google Home device its self then I misunderstood your thinking. and we'd need to talk to HG  I believe there are some projects for this on GitHub.

**Comment by tuicemen** [comment]
The devices showing up in the app lets you know if the Alexa devices can see them after initial discovery and connection the app will tell you if these devices are still on line if they're no seen as online Alexa devices can't control them.
I've not done to much in the way of HA with my Google mini though I did manage to get it working with one of my old PC programs using the Samsung  SmartThings developer portal.
this could be done with HG as well however for most users it would be a bit much to setup.

**Comment by genemars** [comment]
@tuicemen I am just trying to follow same approach as HomegenieEchoBridge and HABridge (emulating UPnP devices like PhilipsHue bridge or Belkin WeMo devices).
How did you make alexa see your x10 devices? Is this still using HABridge?

**Comment by tuicemen** [comment]
> How did you make Alexa control your x10 devices? Is this still by using HABridge?
> Did you have to do some configuration of any sort in the Alexa app?

x10 control was done in HA-Bridge by pointing to the HG API for each device on/off/dim call.
Nothing needed to be done in the Alexa app HA-Bridge told Amazon the devices configured then once a command was given to the Alexa app it forwarded the info to HA-Bridge so it could then tell HG what device to turn on/off/dim

@mralapete  I believe the info is saved however when you open the device options it displays the first feature option even if nothing was saved for it.
Maybe HG can handle more then one feature option for each device I've never tried that.
this issue that your pointing to is the one simular referenced in #330 for security modules But I can indeed confirm the settings are saved for the security modules

**Comment by mralapete** [comment]
@tuicemen We’ve already done the HA Bridge thing in HG. The idea was to integrate the whole process into HG so HG users didn’t have to worry about installing a 3rd party software to achieve this.

Gene will need an Amazon Echo to test his concepts. He is trying to develop this concept in the dark.

I know why the settings are not being retained in the devices. We’ve come across this before. They need to be retained because they depend on the program they are assigned to

I just hope some of the more experienced programmers come back on board to help with the testing. HG really needs them.

You really should concentrate on recovering from your illness. HG is a marathon not a sprint. No quick fixes.

**Comment by mralapete** [comment]
@tuicemen while other HG users may not be commenting here they are following progress. I do understand exactly what Gene is trying to do. I'm also pointing out to him what progress had been made on this subject so he doesn't duplicate effort.

We need to keep the testing ordered as has been done in the past. It is then easier for others to follow what works and what doesn't so Gene can build on what does. The "best boy" in the class approach doesn't work for anyone. 

My feelings on the Alexa is not relevant here. Why you even mentioned here is beyond me. Other HG users have requested this function to be integrated into HG in the past couple of years and others have even managed to make some progress on this. Hopefully Gene can use some of this work to develop a solution.

Remember this GitHub is purely about HG. There are other forums out there should you wish to discuss matters outside of this subject.

**Comment by mralapete** [comment]
@tuicemen best to keep this on topic, 

integration of Alexa device control within HG without the need for an external server like HA Bridge. I'm sure Gene knows what approach to take with this and will do so in his own good time. The external HA Bridge approach has already been well documented and implemented and can be seen in the old homegenie forum.

**Comment by tuicemen** [comment]
> Ok @tuicemen I had a brief look at the HomegenieEchoBridge code and I think it has a similar approach and, correct me if I am wrong, this require a real Echo device connected to the local network


I decided to give this HomegenieEchoBridge another try, now that I have a little better understanding of how HG works and how to install interfaces and such. 
It does work and with out the need for a real hue hub on the network, as I suspected.
 It does take a couple of HG service restarts (and maybe even a reboot) before it actually kicks in.
It detects all HG X10 and Zwave device modules (as well demo modules which I'm not fond of) so it still needs work there. Possibly your work with enabling Virtual UPnP devices and allowing to select which to use could be utilized there. The other drawback is this doesn't work with Google Home. However Google has decided to go the cloud route for there HA control eliminating local bridges. That may put a kink in your plans to include Google in HG.

**Comment by mralapete** [comment]
@tuicemen so what procedure did you carry out to get this enhancement to work. I'm assuming that there is no 3rd party software or hardware involved here. Maybe you could outline exactly what you did for the benefit of other users.

**Comment by mralapete** [comment]
@genemars just came across this GitHub using Fauxmo scripted in Python and proven to work with Alexa. When you get a moment coukd you have a look at it and see what you think. https://github.com/makermusings/fauxmo

**Comment by tuicemen** [comment]
@mralapete this looks very simular to what  Gene is working on
https://hackaday.com/2015/07/16/how-to-make-amazon-echo-control-fake-wemo-devices/ 
However this is very old and much has changed with Amazon and Alexa since this article was published. The python script may have some usable info.

**Comment by mralapete** [comment]
@tuicemen we just need to know how you got Alexa to discover your HG devices using Genes recent addition to v34. There's many hacked versions of a solution out there but no single one seems to work for everyone. You mentioned you needed to reboot or restart the service a number of times for this to happen and again I'm assuming you're just testing with HG and an Alexa.

**Comment by tuicemen** [comment]
@mralapete please re read my reply to Gene. I didn't state I had Alexa working with Genes recent addition to v34.
I used the HomegenieEchoBridge interface to test his theory of it requiring an external Alexa hardware device (Hue Hub, I assume was his meaning).

However it does work on Genes recent build but also worked on the build prior.
I'm not convinced this is what Gene is looking for as it doesn't use Virtual UPnP devices. It would be cool to integrate that if possible strengthening it thought. The Philips hue integration has issues as many pointed out with HA-Bridge

**Comment by genemars** [comment]
It seems that the UPnP virtual devices (which emulates WeMo Switches) **will only work with 1st generation Alexa**. Also other approaches like Philips Hue Bridge emulations (eg. HomeGenieEchoBridge) will probably not work if Alexa 2nd generation is used.

They are purposedly forcing users to register with third party (vendors) service providers such as the WeMo website or the Philips Hue website. I believe that the user should be free to choose if routing smart devices activitity through the internet.

So I can consider this task closed because I am not going to create further hacking to achieve this... I'd rather create necessary services and Skills/App to make HomeGenie interoperate with Google or Amazone the official way.

**However** the fact that now HG can emulate and implement UPnP devices and services out of the box is a very good thing for all other non-Amazon and non-Google solutions that aim to create discoverable and interoperable services on a local network that not require the user to expose his smart devices to the internet.

**Comment by tuicemen** [comment]
@genmars Actually all my amazon devices are second gen. Which explains the issue for me with the UPnP. However the HomeGenieEchoBridge as I stated can and does work in GH. I feel your right though the skill most likely would be the best approach and less or no hacking of existing code.

**Comment by mralapete** [comment]
Yes the way SSDP is being handled by the 2nd generation of Echo seems to be the problem. I asked someone who owns a 1st generation Echo to run HG on a Pi to test your code. It looks like he succeeded but this will not be a solution going forward. 

@genemars Still working on Fauxmo code as it seems there is a solution to the problem. I'll report back with results soon. Copy of GitHub issue and resolution on the following link. Looks like a change in ST definition may be the way foreword here. A bit of a hack in this case but it may work. https://github.com/n8henrie/fauxmo/issues/38

**Comment by mralapete** [comment]
@genemars in the meantime the HA Bridge server could be off loaded to a second Raspberry Pi for those looking for Alexa functionality working on that platform. Simplest and cheapest alternative all round.

**Comment by mralapete** [comment]
@genemars there was mention of introducing Broadlink RM hardware into HG but you are aware of GDPR issues under EU law that have caused a malfunction. https://vn-my.com/watchvideo/how-broadlink-were-almost-ruined-eWMiShhQL5s.html

**Comment by mralapete** [comment]
@tuicemen not really bothered now that Gene has opened up the UPnP library in HG. Loads of easier options available now. Glad you got sorted.

**Comment by mralapete** [comment]
@genemars just to update on this thread. The HomeGenie EchoBridge is actually functioning correctly in your latest release v35 without the need for any 3rd party solutions like HA Bridge. It is discovering HG devices via Alexa and turning them on/off. You may want to include this in the stock HG install as HG doesn't restore user defined MIG programs which means every time you update and restore you need to reinstall HG EchoBridge.

**Comment by genemars** [comment]
HG restore functionality will restore MIG programs only if they are installed from the package repository (options->maintenance menu in HG UI).
Submit *HomeGenie EchoBrigdge" package by making a pull request here:
 https://github.com/genielabs/homegenie-packages
This way it can be installed from homegenie package manager and also restored correctly.

**Comment by mralapete** [comment]
@genemars I don’t have write permission for that

**Comment by tuicemen** [comment]
The latest update to 36 kept the HG echo bridge and I didn't need to re-install or re-enable. Nice!
However I have one issue which I'm not sure is HG or the interface or both.
If security is enabled on HG (passworded) the echo bridge stops working removing the password enables the echo bridge to work again

**Comment by Bounz** [comment]
This is because HGEchoBridge communicates with HG via HTTP API and doesn't use Basic Auth.

**Comment by tuicemen** [comment]
@Bounz  thanks, looks like another enhancement for the Echo Bridge is needed, or users to run two instances of HG one with Echo Bridge one with security enabled (if they wish remote access).

**Comment by mralapete** [comment]
@tuicemen if you haven't already updated the HGEB might be worth doing. Looks like dimming issue has been resolved https://github.com/davidwallis3101/HomegenieEchoBridge

Not sure if Gene did the pull request himself. Might explain why HGEB remained after your update. The HGEB program certainly needs a bit of work but I did point out to you the HG is not the most secure application out there. Just look at your email credentials being broadcast in plain text. Make sure you have additional security enabled when using it.

**Comment by tuicemen** [comment]
@mralapete thanks, I did get notification of the update but not updated yet. I don't use dimming but always like to be running the newest versions

**Comment by genemars** [comment]
@mralapete and @tuicemen you're talking about two different things:
- restoring a backup from a fresh install (that won't restore HGEB since it is not found in the homegenie-package-repository)
. upgrading HG to a new version from maintenance menu (that just updates new files without removing anything that is already in place: eg. a manual HGEB install)

@mralapete HG does implement SSL for emails. So it should be secure like SSL.

@Bounz I'm glad to see you here. I see you started a new HG repo and I wonder if there are chances we can still join our efforts trying to mantain the same repo

@ALL there is a new born in HG family and its name is [**HomeGenie Mini**]() =) a small stand-alone Wi-Fi enabled device that costs about $20 and and that is already a working product even if in a beta stage.

Is there any of you interested in HG-Mini? I had a problem with the first PCB batch so I will have to wait 2 weeks more before I get the new prototypes but you can already order and get your board using the Fritzing service which sells 3 boards for about €18. 
HG-Mini is very easy to use: just plug the device, push the WPS button and it will automatically register in your Wi-Fi network. Then HG-plus will autodiscover it. Also HG-server already supports and integrates HG mini devices though MQTT.

**Comment by mralapete** [comment]
@genemars I'm certainly interested in learning a little more about HomeGenie Mini. Could you describe your concept in a little more detail. What market are you aiming this product at. What is driving your concept. Is it based around an ESP8266.

You refer to HG-plus and HG-server. Are these two different products.

I strongly suggest you re-establish a forum where HG users old and new can discuss and exchange ideas now that you have a marketable product.

In fairness @Bounz established his HG repo a good while back when development halted on HG and his forum has enabled HG users to continue to help each other. Obviously he will be the best person to answer the question about joining repos but remember why he had to set it up in the first place.

**Comment by tuicemen** [comment]
@genemars  I also am interested in the HG-Mini which sounds like a CM19 on steroids.
To bad it didn't have X10 PLC or ability to plug in a USB device like the CM15 or a Zwave dongle.

Unlike @mralapete I don't believe you need to recreate a HG forum (you most likely don't have the files to resurrect the old forum anyways)just be more active on one discussing HG. @Bounz has the HomeGenie.Club where users already discuss both HG repos.
There are other forums available like the forums.x10.com that now has a special section for the PiX10Hub image featuring HG.

**Comment by genemars** [comment]
@mralapete I don't have plan to open a new HG forum in the near future, but I will be looking at @Bounz and @tuicemen forums sometimes or maybe better I'll be there anytime you want me to partecipate to a particular topic.
So to clarify HomeGenie products line consists of:
- **HomeGenie Server**
is the smart home server for Windows/Linux/Mac  
- **HomeGenie Mini**
is a miniaturized version of *HomeGenie Server* that runs on microcontrollers (ESP8266) and that features X10 RF protocol, temperature and light sensors, expansion port that can be used for various purpose (eg. to connect and control up to [4 relays](https://www.amazon.com/Dorhea-Channel-Protection-Expansion-Raspberry/dp/B07GKML96X/ref=sr_1_9?ie=UTF8&qid=1549133052&sr=8-9&keywords=4+relay+board+arduino) mappable to X10 units).
- **HomeGenie Plus**
is a smart home client app for Android that can connect to:
     - HG server
     - HG mini
     - Philips Hue bridge
     - TP-Link
     - Belkin WeMo
     - LIFX

**Comment by mralapete** [comment]
@genemars as you know X10 has a very limited appeal theses days. Personally I just use it for light control. I’d focus more on Z Wave and some of the more modern protocols as they will have broader appeal. 

I can already see an application it could be used for that our company is currently developing. Needless to say it won’t involve X10 from a commercial point of view. 

You could pm me and I can give you further details.

**Comment by tuicemen** [comment]
There is the ability to use the serial connection for other devices however a USB connection would I suspect add more appeal. X10 appeal may be dropping off but it is still has a strong user base in North America.

**Comment by genemars** [comment]
@mralapete and @tuicemen 
as already stated before, HG Mini is meant to be a stand-alone device not a gateway.
HomeGenie Server can already do Z-Wave and X10 so there's really no need to "duplicate" HG server functionalitites into HG-Mini.
The fact that HG Mini has a 433MHz transceiver is because there are many smart home devices that operates on that RF range, so beside the already supported X10 RF protocol, maybe more protocols will be added in the future. This is the only "gateway" functionality planned for HG Mini.
So @tuicemen even if I said I would think of it, after that reasoning I definitely will not add a USB port to it.

**Comment by tuicemen** [comment]
So is the RF software tunable like the Broadlink RM? That would be most useful.
I understand not wishing to add a USB port.

**Comment by tuicemen** [comment]
@genemars  is there a place to post issues and enhancement request for the HomeGenie Plus?

**Comment by genemars** [comment]
@tuicemen yes. Join the HG plus Beta program from Play Store.
[How To Become A Beta Tester For Google Play Applications](https://www.youtube.com/watch?v=J0rFw4gZjqw)
The you'll able to write feedback.

**Comment by tuicemen** [comment]
Thanks doing it now!
