### ISSUE TITLE
Broadlink RM Pro interface? (Feature Request)

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#356]
This little inexpensive IR/RF sending device has so many possibilities.
 One such advantage is being able to learn and send X10 Security codes. Support for this would also open HG control of Broadlink devices which are growing in number.

Since there are a number of free methods for capturing RF or IR codes with these HG would only need to be able to send the code simular to what other HA programs do now.
Currently I use HA-Bridge to interface with the Broadlink RM But my hope is to eliminate the need for HA-Bridge now that I have HG seeing devices for Alexa
The Broadlink RM also has an on board thermometer which could be useful  for setting up temperature based macros for the room it is located in.
There are a number of repositories for this  but this one seems to have the ability to learn/send codes, get the temperature as well some specific Broadlink smartplug options.
https://github.com/mjg59/python-broadlink

**Comment by kaykingtoo** [comment]
GRAND REQUEST!  Thank you!  We too use HG with broadlink RM pro thru HAbridge to have HG transmit security codes.    Believing in KISS, elminating the habridge program with a native built in Hue type module in HG would be great.

**Comment by tuicemen** [comment]
I've been digging into this a bit more each chance I get.
Using the CLI files from the link in my OP I've been able to discover my Broadlink RM Pro and get its temperature.  Note: this is the broadlinks temperature not the room temperature
I know absolutely zip about python so for me to create some sort of interface or program may take some time. As well my programing season is almost done.
The files in the CLI folder are to be used in a command line interface (terminal) Thus the name for the folder.
Once the prerequisites are installed you simply type `python broadlink_discovery` this gets you your Broadlink info which is required for sending or learning commands.
You then use the broadlink_cli file to do the learning and sending.

**Comment by tuicemen** [comment]
Success! I can now send arm and disarm codes to my X10 security console via a terminal command.
now just to create a HG program utilizing these things.

**Comment by kaykingtoo** [comment]
FREAKING AMAZING!!!!!!!!!!Sent from my Verizon 4G LTE smartphone

-------- Original message --------

**Comment by kaykingtoo** [comment]
With full byte access, does this fix the all keyfobs have same code also?Sent from my Verizon 4G LTE smartphone

-------- Original message --------

**Comment by kaykingtoo** [comment]
Wow!!!!  Light at the end of the tunnel!!Sent from my Verizon 4G LTE smartphone

-------- Original message --------

**Comment by tuicemen** [comment]
This uses the Broadlink RM it has no affect on how HG handles the Keyflob codes

**Comment by tuicemen** [comment]
I managed to create a program which makes calls to the command line to send commands to the Broadlink this also auto detects the Broadlink on each HG service start so that does solve that issue.
This uses a generic switch widget.
Using the terminal command line to send Broadlink code is extremely slow and may be to slow for many users for sending, however this will open the door for Broadlink smart devices to work with HG.

 I may have to get my feet wet and learn python so HG can talk directly to the Broadlink.

**Comment by tuicemen** [comment]
I now have two programs created for the Broadlink One shows its status(IP, mac Address, and the Broadlink device ID detected) this info is needed for the Broadlink sender program but is serves a second function (for me) it tells the last time checked and if nothing is detected that tells me it has been unplugged which happens more often here then any other plug in device. These still use the command line from a HG  however now that the sender program uses hardcoded info for the Broadlink response time has improved.
There are a few C# Broadlink programs on GitHub so integrating directly into HG should be possible.
I'll dig into those C# codes as time permits.
I've not created a learning program for the Broadlink however it is possible to do this using the command line interface. I use Broadlink codes already learned using other methods so making a special program was not needed in my case.

**Comment by tuicemen** [comment]
> With full byte access, does this fix the all keyfobs have same code also?

Actualy HG sees each Keyflob RF security signal and it is possible to have HG respond to a specific Keyflob you just can't use the Keyflob widget status as all keyflobs will activate that  keyFlob widget and change its status.
