### ISSUE TITLE
Enabling HG Password protection blocks some addons

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#359]
### Expected behavior
access to additional HG user created addons to perform with Password protection the same as with out 

### Actual behavior
Enabling password protection stops some addons from working(EchoBridge, Generic IP camera)

### Steps to reproduce the problem starting from a fresh install

  1. enable Generic IP camera and set up camera info
  2. enable Echo Bridge and get Alexa to discover and control devices
  3. enable password protection of HG
  4. restart HG service and test addons camera info is lost (not sure if reentering info fixes that yet)and Alexa fails to see devices

### Specifications

  - Version: 1.2-stable.34  - Operating System: Raspbian stretch lite
  - .Net/Mono runtime version: 5.4
  - Hardware configuration: pi Zero W with Cm15 or Cm19

#### Additional configuration notes
Every thing seems to work fine till Password protection is added.
I believe this worked in older versions of HG but it has been several months since I had tested the Password protection. Being home during the winter and always home I disabled it while testing new HG builds.

**Comment by mralapete** [comment]
Generic camera working fine here with HG user name and password. EchoBridge author would be the best person to take this matter up with. It's not been certified to run on this HG release. It was created around a fork of the HG project.

**Comment by mralapete** [comment]
Works on all variants. Again a look at the logs at the point of program failure would give a better indication what's causing your issue. That program fails regularly owing to security cert issues. I'm sure if Gene sees your logs he could quickly identify your problem.

**Comment by tuicemen** [comment]
>           Works on all variants. 

OK, reloaded password and never lost the camera info this time around and Generic camera addon still works. :)
Not sure what caused the issue last time, maybe a corrupt update download or corrupt HG backup upload.
