### ISSUE TITLE
security system broken with stable 35

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#360]
With the current (35) release the security system requires being recompiled to work again.
I had figured this was just my system but it appears others are seeing this as well. 
Also it again doesn't retain its Armed state if set to Armed Home or Away and a reboot occurs #331

**Comment by tuicemen** [comment]
the issue is still present in 36

**Comment by genemars** [comment]
@tuicemen I've tested this in Linux and it is working. Did you try on a fresh install?

**Comment by tuicemen** [comment]
If the security is armed and a reboot occurs the security module reverts to disarmed. happens on all three Pis I run.
I've not tested on a fresh install only on a updated HG, will do that today.

**Comment by genemars** [comment]
> If the security is armed and a reboot occurs the security module reverts to disarmed
@tuicemen I think this has always been that way, but this can be a feature request opening a new issue.

**Comment by tuicemen** [comment]
Ok I noticed a HG service restart also reverts the security to disarmed.
Writing a new image with HG now to test the recompile issue. However I suspect any new build will not display this issue with having to recompile the security module until a update is performed.
should I install 35 then update to 36 for the test?

**Comment by genemars** [comment]
ok I will check this out 🙂

**Comment by tuicemen** [comment]
Version 37 appears to have fixed the security re configure issue. Thanks.
As well Thanks for adding the security system retaining its status on a service restart!
