### ISSUE TITLE
Home Genie Not Responding after updating to 1.2-stable31 and beyond

### ISSUE THREAD

**Issue by stang70man** [genielabs/HomeGenie#362]
### Expected behavior
Expect HomeGenie to respond properly to port 80 requests after updating

### Actual behavior
Page cannot be displayed on HomeGenie running on a Raspberry PI after update to 1.2-stable.31 and beyond. 1.2-stable.30 works fine after rolling back to that version.

### Steps to reproduce the problem starting from a fresh install

  1. Updated from 1.2-stable.19 to 1.2-stable36
  2. Tried Restarting the homegenie.service manually
  3. Tried Restarting Raspberry PI
  4. Rolled back to 1.2-stable.18 (couldn't find 1.2-stable.19) and HomeGenie Responded properly
  5. Updated manually through versions from 1.2-stable.18 through 1.2-stable36 and it quit working at 1.31 and beyond after update.

### Specifications

  - Version: 1.2-stable.31 (and beyond)
  - Operating System: Raspbian Jessie
  - .Net/Mono runtime version:  3.2.8
  - Hardware configuration: Raspberry PI 2 B+

#### Additional configuration notes

I did an apt-get update apt-get upgrade and rebooted before installing version 1.2-stable.36 and rebooted and still no joy.

**Comment by tuicemen** [comment]
I suspect your mono version maybe the issue but a log file should produce more info

**Comment by mralapete** [comment]
I don't recommend the latest Mono version with Raspbian Jessie. Might be worth taking a backup of your HG and doing a fresh installation of Raspbian Stretch. From there follow the instructions on the homegenie.it site. Once HG is installed you could restore your HG backup.

This method will give you Mono 4.6 which should resolve your problem. 

Should you wish to install the latest version of Mono from the Mono Project follow these instructions before you attempt to install HG and after you have installed Raspbian Stretch.

sudo apt install apt-transport-https dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/debian stable-raspbianstretch main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
sudo apt update

**Comment by tuicemen** [comment]
@stang70man did updating your mono fix your issue?

**Comment by stang70man** [comment]
Just completed the mono upgrade to the newest version for Raspbian Jessie and then upgraded to HomeGenie 1.2-stable.37 and all is well. HomeGenie newest version is working once again. Thank you to all who provided advice!
