### ISSUE TITLE
Security module feature request

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#363]
Currently the security module if Armed (away or home) and a reboot or service restart occurs the security module reverts to Disarmed. This renders any security options (macros) in HG useless.
HG needs to remember last state of the security display  for when these things occur.
see #331  for more info

**Comment by mralapete** [comment]
@LostDog88 it’s always advisable to recompile programs after an update to check consistency.

The problem you experienced is not related to the the feature requested here. This feature has never appeared in HG before. In fact I’ve never seen it requested before either.
