### ISSUE TITLE
Unable to add additional security key flobs

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#366]
**_This issue is not a security related one even though related to_ #365** 
I'd love to add a second or third x10 security flob to HG. However that currently isn't possible even though HG sees its code. If a security key flob is already configured HG sees the second or third as the one configured even though the RF security codes that HG sees are different. 
These are security devices but I use a lot of x10 security modules for other things in fact I don't even use a X10 Security console at my city place.

**Comment by genemars** [comment]
can you tell which part of the raw RF message can be interpreted as the address of the remote?

**Comment by tuicemen** [comment]
since HG sees each Security key flob I have as a security key flob there must be part of the raw RF message.
I just got back to town so I'll play around a bit this evening with the RFs.

**Comment by tuicemen** [comment]
I don't see any thing in the raw RF message that is unique to a key flob all my security modules Raw RF start with 29 and end with 00 the other bits are different.

**Comment by genemars** [comment]
I thought that only the last two bytes would change using different security remotes.
If you press ARM on one remote and the the other one the first 4 or 5 bytes should be the same.

**Comment by tuicemen** [comment]
Here are the Raw Arm codes from two different  (KR10A) Security Key flobs
29 9B 95 06 F9 AF 00
29 D3 DC 06 F9 F7 00 
So it appears there are some similarities  for the Raw ARM codes maybe I was comparing arm to disarm ?
Raw Disarm codes from the same two (KR10A) Security Key flobs are:
29 9B 94 86 79 AF 00
29 D3 DC 86 79 F7 00
