### ISSUE TITLE
Abnormal CPU usage

### ISSUE THREAD

**Issue by noliono** [genielabs/HomeGenie#374]
### Expected behavior

No abnormal CPU usage.

### Actual behavior

Since my update to the last version of HomeGenie, HomeGenie need to be reboot because full use of 2 or 3 core CPU :
![Capture d’écran de 2019-03-25 20-53-27](https://user-images.githubusercontent.com/10108085/54949843-3f4ca680-4f40-11e9-85a5-5e931b0dc73d.png)

Did some one have the same problem ?

### Steps to reproduce the problem starting from a fresh install

  1. I didn't try to start from a fresh install
  2. I have several program (natif or my own one)
  3.

### Specifications

  - Version: 1.3-beta.2
  - Operating System: Raspbian GNU/Linux 9 (stretch)
  - .Net/Mono runtime version: 4.6.2
  - Hardware configuration:

**Comment by genemars** [comment]
Try disabling all custom programs. Also disable the **UPnP emulation** program (under Devices and Things) which has a bug that cause HG to hang after a few days.

**Comment by noliono** [comment]
> Try disabling all custom programs.

I try to disable most of my custom program but i need to keep some needed but i try to disable more now (not still all). 

> Also disable the **UPnP emulation** program (under Devices and Things) which has a bug that cause HG to hang after a few days.

I remember that so i have already do it :)

But it seems i am the only one with this problem so i close the issue. Thanks.

**Comment by noliono** [comment]
I have finally solve my problem after severals try. I think the good one was to switch Mono version from v4 to lastest v5. By using a different repo than the default one with this modop :
https://www.mono-project.com/download/stable/#download-lin-raspbian
