### ISSUE TITLE
OpeneWeatherMap possible bug

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#380]
My icons generated by the Openweather map at the top of the web UI indicate temperature followed by the correct value. the rain icon displays followed by a value which changes to values even though I receive no rain and the widget displays no rain value. some times it reports correctly other times it is way off as shown in the attached
<img width="339" alt="Info" src="https://user-images.githubusercontent.com/25393840/55268693-8ac5c400-5262-11e9-95f5-50d40a9e1ed5.png">

**Comment by genemars** [comment]
@tuicemen I am not sure I understood what you mean. Where's the problem in the above picture (beside the fact that is still really freezing out there :)).

**Comment by genemars** [comment]
@tuicemen if you refer to the **39** value in the top bar I guess that is the humidity, not the rain value.

**Comment by tuicemen** [comment]
@genemars  your correct after adding the humidity Value to Openweather is when I noticed this prior it was showing 0 matching rain value. My mistake!
