### ISSUE TITLE
MQTT Interconnection Fail

### ISSUE THREAD

**Issue by neocit** [genielabs/HomeGenie#381]
### Expected behavior
I have 2 Raspberry Pi 3+ with Homegenie.
1 for Pool
1 for Garden

With version 1.1.-526 and 527 they work fine with MQTT broker on a other Server.
Switch and Sensor are Visible in both HG.
If i press Switch on in HG Pool it change in HG Garden to. When i switch it off on HG Garden, HG Pool update the state correctly.

After upgrade resp. New Install of Homegenie 1.3.beta2 they wont be visible in the Homegenie. The thermostate from Pool send mqtt to system. I can reveive the state in OpenHab. But HG Garden dont see nor receive Infos.
When both HG are on 1.3.beta2 they wont connect together.

I think there is an Issue with MQTT

### Actual behavior

I have tried with HG 1.1.526 on Pi Garden and 1.3.beta2 on Pool.
They cant connect.

When i changed/replaced the Program 77 MQTT on 1.3.beta2 with the old code.
I will receive the state info from Pool on thr HG Garden but if i switch off a Pool Switch nothing changed on the HG Pool.
I think HG Pool with 1.3.beta2 dont receive anything. Sending will be OK.

### Steps to reproduce the problem starting from a fresh install

  1.
  2.
  3.

### Specifications

  - Version: 1.1-stable.527
- Version: 1.3-beta.2
  - Operating System: Raspbian Stretch
  - .Net/Mono runtime version:
  - Hardware configuration:

**Comment by genemars** [comment]
Fixed by **v1.3-stable.3**.
