### ISSUE TITLE
Update notification flag still displaying after successful update

### ISSUE THREAD

**Issue by homeautomate8** [genielabs/HomeGenie#385]
### Expected behavior
Yellow update notification arrow/flag in the top right hand corner of the screen should clear after a successful update

### Actual behavior
Yellow update notification arrow/flag in the top right hand corner of the screen still displaying after a successful update

### Steps to reproduce the problem starting from a fresh install

  1.Update from v1.3-beta.2 to v1.3-stable.3 
  2.Update from v1.3-stable.3 to v1.3-stable.4 
  3.

### Specifications

  - Version: 1.3-stable.4
  - Operating System: Raspbian Stretch Lite
  - .Net/Mono runtime version:5.4
  - Hardware configuration: Raspberry Pi 3

#### Additional configuration notes

@genemars As outlined above since update from v1.3-beta.2 to v1.3-stable.3 and update from v1.3-stable.3 to v1.3-stable.4  the yellow update arrow still displays even though a successful update has been performed. Clicking on the yellow arrow still shows update 3 and 4 available to be updated yet in the About Homegenie tab it confirms that the system is updated.

Any idea what may be causing this. I assume the updater routine is not updating this flag after a successful update.

**Comment by tuicemen** [comment]
have you tried redoing the update?
I don't see this on my RPi running Stretch Lite

**Comment by homeautomate8** [comment]
Of course. I tried all the obvious before I opened the issue. I’m quite familiar with HG and generally know what to look out for. 

I’ll wait till @genemars reads the issue and see what his take is on it.

**Comment by genemars** [comment]
I'll check this out.
