### ISSUE TITLE
RF commands to Security onsole SC9000

### ISSUE THREAD

**Issue by andros19** [genielabs/HomeGenie#386]
I would like to use HomeGenie and CM15Pro to send X10 RF commands (ArmAway, ArmHome, Disarm) to my security console (SC9000).
In this way I will be able to use the scheduler to schedule the time when the console will be armed or disarmed.

**Comment by tuicemen** [comment]
Currently many of us are using a Broadlink RM Pro to handle Security RF send events and use the Philips Hue program to talk to HA-Bridge.
I'm not sure if HG is capable of sending raw security RF to arm the console but I've been looking into it.

**Comment by andros19** [comment]
If I remember well, 4 - 5 years back when we were just starting with HG
there was support for the SC9000, but then it was removed because it was
considered obsolete after the introduction of the security program in HG.
Some of the members of the original forum may correct me if I am wrong.
In any case since some of us are still using the X10 security consoles it
would be nice to be able to control them via HG and the scheduler.

**Comment by andros19** [comment]
@Tuicemen I have seen your previous posts in another thread about the
broadlink RM Pro and I am already considering to buy it as it is not so
expensive.
I want to use it both for RF and IR but I do not know if the RF range would
be sufficient for the place that I want to put it.
Also I am not sure if I will be able to set it up to work with HG as I have
never used HA-bridge before.

**Comment by tuicemen** [comment]
> there was support for the SC9000, but then it was removed because it was
> considered obsolete after the introduction of the security program in HG
@andros19 
That sound promising I don't have a sc9000 but a obsolete ds7000 which responds to the same codes from my understanding. I'll continue to dig into the code to see if I can find a solution.
The RF range on the Broadlink is quite good when not in learning mode.  The signal only needs to make it to a Cm15 if the console is to far I suspect. However there is always the RF repeater which I've had extremely good success with (over 150 feet and through an exterior wood/cement wall).

**Comment by andros19** [comment]
@Tuicemen I will order the broadlink and try it since I have also other use
for it.
It will take a couple of weeks for shipment to where I am, but I will let
you know the result after I try it.
In the meantime if you have any success with the code in HG that would be
very nice.

**Comment by tuicemen** [comment]
I'll continue to look into the HG code.
I don't believe the Security RF receives /send needs to be tied directly to the security console program.  You could use those raw RF codes for other things (exactly what I've no idea) 
from my understanding @genemars  just added Raw x10 RF sending from the CM15 in one of the last releases, maybe that holds the key.

**Comment by andros19** [comment]
@Tuicemen
Which RF repeater are you using?
I am very disappointed because I bought two pcs of SR9231 and none of then
seems to be working.
Don't know if any one else on the forum had used these repeater

**Comment by tuicemen** [comment]
I use the newer North American SR751 Repeater
https://www.x10.com/x10-pro/specialty-devices/couplers-repeaters/sr751.html 
I also have the SR731 (North American version of the SR9231) but it doesn't seem to have the same good range.

**Comment by andros19** [comment]
The SR9231 is totally useless. Doesn't seem to work at all.
In any case I will wait until I receive the Broadlink RM Pro and try it. I
may not need a repeater.

I also tried to use the RF commands in HG using the CR15pro but also
doesn't seem to work with security commands.

**Comment by tuicemen** [comment]
HG currently doesn't seem to capture the total security RF code bits. nor allow for the extra bits required to be transmitted. :(
As indicated in issue #387 HG needs to be updated to capture and send that info in order to arm/disarm X10 security consoles.
I find the Broadlink to have better transmit range then my CM19 and CM15 but I've not done extensive tests. The learning RF range (receive) is very short (under a few centimeters for X10 security RF)

**Comment by andros19** [comment]
Yes I have been following the exchange of messages with @yorlik-too.
We wii have to wait for this.

The learning range for the Broadlink should not be a problem as long as the
working range is OK. I should have the unit in about one week and then I
can test.

**Comment by andros19** [comment]
@tuicemen Finally I received my Broadlink RM pro+ and have set it up to work with Google Assistant through the Broadlink App. What a Great Gadget this is
I have tested it with learned RF commands for my security console SC9000 and is working fine. Range is just enough. By the way you were right about the very short range in learning mode.

Now what remains is to intergrade Broadlink into HG. 
I know there is a way using HA Bridge which I have not tried yet, but I also read your post in the HomeGenie Club about inrgrading code in HG and avoid using HA Bridge. The problem is that I am running HG on a Windows based lap top and I noted that the driver for the Broadlink is running under Linux.
I have Ubuntu running on another machine and I am not sure if I can use that to create the additional program to upload in HG. 
Any advice will be greatly appreciated.

**Comment by tuicemen** [comment]
HA- Bridge has Broadlink support intergrated into it and works well on Windows using the included HG Philps Hue plug in.
I ran it this way until I modified the HG hue script to allow password protection of HA-Bridge.
I then started to play with the Broadlink driver but yes my work with it is on Linux with a RPI board.

BWSsystems is currently working on a helper for HG which should make setup with HG much simpler.

**Comment by andros19** [comment]
Thank you very much for your prompt reply. Greatly appreciate it.
I will try both ways and let you know the outcome.

**Comment by mralapete** [comment]
@andros19 you might want to review this post I made on this subject https://github.com/genielabs/HomeGenie/issues/396

**Comment by tuicemen** [comment]
@andros19  as you can see @mralapete  has this working with the Cm15 Pro I also have this working with a Cm15A and a DS7000. No need for the Broadlink however I use the Broadlink for IR which the Cm15A doesn't have.
There are Windows C# programs for the Broadlink on GitHub here so you may wish to look at one of those. My HG Broadlink program should be easy enough to modify to use one of them.
In any case I believe this issue can be marked as closed.
