### ISSUE TITLE
X10 RF module decoder (built in HG program "X10 RF" module)

### ISSUE THREAD

**Issue by yorlik-too** [genielabs/HomeGenie#387]
### Specifications
  - Version: 1.3-stable.3
  - Operating System: 
  - .Net/Mono runtime version: latest
  - Hardware configuration: pi
#### Additional configuration notes:  none required

So the X10 RF module tracker shows max 6 bytes.  Normal X10 on/off sigs are 5 bytes so good.  Security is more bytes...  

So I can go to config->groups->page->X10rfmodule parameters  and check Receiver.RawData and see 7 bytes,  Still not enough to represent the full security code that it sees.

I request you open up the Receiver.RawData to show ALL bytes;  if unsure how many required, how about setting it to display 32 bytes max?

THEN I can configure api call HomeAutomation.X10/RF-Control.RfSend,bytes to send that code on demand.

**Comment by tuicemen** [comment]
@genemars  & @yorlik-too you may find this a bit helpful
https://bfocht.github.io/mochad/x10_rf_security_extended_address.html

**Comment by yorlik-too** [comment]
GREAT!  confirms my code is right!  I believe Gene is not sending last
byte so it does not work...  

On 2019-05-07 15:50, Tuicemen wrote:

> @genemars [1] & @yorlik-too [2] you may find this a bit helpful
> https://bfocht.github.io/mochad/x10_rf_security_extended_address.html 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4]. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/genielabs/HomeGenie/issues/387#issuecomment-490230295", "url": "https://github.com/genielabs/HomeGenie/issues/387#issuecomment-490230295", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
 

Links:
------
[1] https://github.com/genemars
[2] https://github.com/yorlik-too
[3]
https://github.com/genielabs/HomeGenie/issues/387#issuecomment-490230295
[4]

**Comment by yorlik-too** [comment]
UPDATE:  
> #### Additional configuration notes: none required
> So the X10 RF module tracker shows max 6 bytes. Normal X10 on/off sigs are 5 bytes so good. Security is more bytes...
> 
> So I can go to config->groups->page->X10rfmodule parameters and check Receiver.RawData and see 7 bytes, Still not enough to represent the full security code that it sees.
> 
> I request you open up the Receiver.RawData to show ALL bytes; if unsure how many required, how about setting it to display 32 bytes max?
> 
> THEN I can configure api call HomeAutomation.X10/RF-Control.RfSend,bytes to send that code on demand.

I believe a complete security RF code is 8 bytes.  

Again, it would be useful if the config->groups->page->X10rfmodule parameters and check Receiver.RawData would show at least 8 bytes rather than 7.  It is probably good that the actual X10 RF widget only shows 6 to prevent easy decoding by unscrupulous folks.

But we really need the HomeAutomation.X10/RF-Control.RfSend to allow 8 bytes be sent.  HG would instantly become much more powerful!  I suspect the present limitation is just a counter value in the code that can fairly easily be changed from present 6? to 8 or 12 or?

**Comment by yorlik-too** [comment]
Any updates?

**Comment by tuicemen** [comment]
I've tried to locate where this may be found in the HG code since there isn't a road map (that I'm aware of) it is proving difficult.
I did locate some code for  handling RF/IR but didn't see a place to edit the bit length though I may have overlooked it.
@genemars  seems to be busy with work or what not so we may have to wait till he can shed some light on this. 
In the mean time I'll continue to dig and if I find the spot to edit the code I'll put in a pull request with the edits.

**Comment by yorlik-too** [comment]
Thanks.  I did not consider looking for keywords in the programs...  I
will try too!

On 2019-05-15 15:24, Tuicemen wrote:

> I've tried to locate where this may be found in the HG code since there isn't a road map (that I'm aware of) it is proving difficult.
> I did locate some code for handling RF/IR but didn't see a place to edit the bit length though I may have overlooked it.
> @genemars [1] seems to be busy with work or what not so we may have to wait till he can shed some light on this.
> In the mean time I'll continue to dig and if I find the spot to edit the code I'll put in a pull request with the edits. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3]. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/genielabs/HomeGenie/issues/387?email_source=notifications\u0026email_token=ALONDR3QQAUXNA6YFEGJZLTPVRPNPA5CNFSM4HLLR6JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVPWDLY#issuecomment-492790191", "url": "https://github.com/genielabs/HomeGenie/issues/387?email_source=notifications\u0026email_token=ALONDR3QQAUXNA6YFEGJZLTPVRPNPA5CNFSM4HLLR6JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVPWDLY#issuecomment-492790191", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
 

Links:
------
[1] https://github.com/genemars
[2]
https://github.com/genielabs/HomeGenie/issues/387?email_source=notifications&amp;email_token=ALONDR3QQAUXNA6YFEGJZLTPVRPNPA5CNFSM4HLLR6JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVPWDLY#issuecomment-492790191
[3]

**Comment by mralapete** [comment]
@yorlik-too you may want to read this issue I opened https://github.com/genielabs/HomeGenie/issues/396
