### ISSUE TITLE
Philips Hue Bridge does not record correct Hue Device Address

### ISSUE THREAD

**Issue by bwssytems** [genielabs/HomeGenie#391]
### Expected behavior
When Hue devices are detected, the expectation is the hue address would be used in the module schema

### Actual behavior
When the hue devices are detected the Hue address is arbitrarily numbered from start of 1.

### Steps to reproduce the problem starting from a fresh install

  1. Add hue bridge in the config settings
  2. restart hue service from widget
  3. The displayed devices are numbered starting from 1 when actually they start from 100 in my bridge.

### Specifications

  - Version: 1.3-stable.5
  - Operating System: Linux Mint 19
  - .Net/Mono runtime version:
  - Hardware configuration:

**Comment by tuicemen** [comment]
Is this using a Philips hue hub with the HG hue bridge program?
I only use HA-Bridge and the device numbers in HG correspond to the number HA-Bridge assigns them.
At least they did for me when I originally first added them to HG.
I don't have a hue hub  nor any true hue devices.

**Comment by bwssytems** [comment]
Nope, I was testing against an ha-bridge I installed. I may have missed a setting then.
