### ISSUE TITLE
HomeGenie does not trun on Raspbian Buster

### ISSUE THREAD

**Issue by ngineerken** [genielabs/HomeGenie#392]
### Expected behavior
HomeGenie just runs as expected

### Actual behavior
HomeGenie fails to start

### Steps to reproduce the problem starting from a fresh install

  1.Have HomeGenie running on Raspbian Stretch
  2.Upgrade from Stretch to Buster (the latest release)
  3.Reboot and HomeGenie fails to start

### Specifications

  - Version: 1.1-stable.527
  - Operating System: Raspbian Buster
  - .Net/Mono runtime version:  Non as Mono is held back 
  - Hardware configuration: Pi3

#### Additional configuration notes
Zwave

**Comment by homeautomate8** [comment]
No Mono no HG. 

Are you saying you’ve no Mono installed or is it just no updating.

You’re way back on HG releases so I’d advise updating to the latest version from the GitHub. 

Possibly install Buster first and then the latest version HG and restore your backup.

**Comment by ngineerken** [comment]
I have upgraded to Buster and reinstalled from GitHub and is fails:

Package libmono-corlib2.0-cil is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  mono-reference-assemblies-2.0 mono-devel

E: Package 'libmono-corlib2.0-cil' has no installation candidate
E: Package 'mono-dmcs' has no installation candidate
pi@raspberrypi:~ $ sudo gdebi homegenie_1.3-stable.5_all.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: mono-dmcs

**Comment by ngineerken** [comment]
I just found that Buster has been made Stable in the repo

**Comment by homeautomate8** [comment]
If your dependencies are not met or package is not available you need to update your sources list.

I suggest pointing your sources list directly to the Mono project if you are having difficulty locating packages in the Raspbian repos.

**Comment by tuicemen** [comment]
HG 1.1.stable had several issues with newer versions of Mono whic were addressed with newer versions of HG. Gene removed and updated several obsolete drivers and code.

**Comment by homeautomate8** [comment]
What issues were they. I’m not aware of any. 

Granted HG remained fairly static at version 1.1 v527 for quite a while. In fact many are still using that version.

If users are experiencing difficulties with either Mono or HG they can build their own version of either.

I’d advise users who are not really familiar with the Raspbian/Linux environment to hold off upgrading their HG install to Buster. 

While it’s reporting stable there’s a number of tweaks needed to the repos to get HG up and running with it stability wise.

**Comment by tuicemen** [comment]
The main issue with some mono versions is HG would fail. I'm unaware what mono version Buster comes with so it may be one of the versions I had tested with 1.1 stable 527. There were issues with security certificates as well if i remember right however which versions had what issues with HG I cant recall.
Users that are not using at least stretch on their Pi will most likely have issues with the newest HG.

**Comment by homeautomate8** [comment]
Just to confirm that the package manager install feature is failing reporting issues with Lirc when trying to install on Raspbian Buster.

You can of course install HG V1.3r3 manually on Raspbian Buster by first installing the dependencies as outlined here http://homegenie.it/ and downloading the .tgz file and tar it into the folder of your choice, usually /usr/local/bin/homegenie

**Comment by tuicemen** [comment]
You can install the latest version of HG on Buster as well you just can't use the installer.
I in fact have HG running on Debian Bullseye  alfa build.
So the issue is not HG won't run on Buster but that the **HG Installer doesn't work on Buster**
A Upgrade to Buster from Stretch can cause all sorts of issues  if just doing a upgrade you need to upgrade Mono as well. I have HG running on a Upgrade of Buster but a fresh install of buster then fresh mono then HG dependencies then HG works better
