### ISSUE TITLE
latest ver not updating X10 security modules?

### ISSUE THREAD

**Issue by kaykingtoo** [genielabs/HomeGenie#394]
### Steps to reproduce the problem starting from a fresh install   

  1.   starting from reboot, they show static and do not change
  2.
  3.

### Specifications

  - HomeGenie Version v1.3-stable.5
  - Operating System: 
  - .Net/Mono runtime version:
  - Hardware configuration:   pi

**Comment by mralapete** [comment]
@kaykingtoo you may want to review this issue I opened https://github.com/genielabs/HomeGenie/issues/396
