### ISSUE TITLE
gocontrol thermostat : No device info was found for manufacturer ID = 014f:5442:5437.

### ISSUE THREAD

**Issue by bwlang** [genielabs/HomeGenie#395]
https://www.gocontrol.com/detail.php?productId=3

### Expected behavior
Thermostat is recognized

### Actual behavior
error message when setup button is pressed
### Steps to reproduce the problem starting from a fresh install

  1. Join gocontrol thermostat to network
  2. discover devices

### Specifications

  - Version: 1.1-stable.527
  - Operating System:  linux
  - .Net/Mono runtime version: Mono JIT compiler version 4.6.2
  - Hardware configuration:

**Comment by tuicemen** [comment]
You realy should be using the newest version of HG and mono. Gene has made several improvements to HG since the version your running.

**Comment by bwlang** [comment]
@tuicemen  thanks for your reply.

I think 1.1-stable.527 must have been prefilled - sorry.!
I just checked ... the actual version number is v1.3-stable.5 (which is the latest I think).

Here is what I see after clicking dismissing the error message:
![image](https://user-images.githubusercontent.com/61636/69007890-e2a85c80-0911-11ea-9ecd-810a15ab0ffb.png)

I do see the thermostat control on the dashboard now, but i can't interact with it... I hope I'm not just misunderstanding how to use this.

**Comment by tuicemen** [comment]
Yep that is the latest version of HG. Sorry I don't  use that control so I can't help with that.

**Comment by homeautomate8** [comment]
Do you have the discovery service enabled in HG. 

Might be worth posting over at the HomeGenie Club Page. There’s not been much activity on the GitHub for some time. Try this link https://homegenie.club/latest
