### ISSUE TITLE
Node Red native support 

### ISSUE THREAD

**Issue by mralapete** [genielabs/HomeGenie#397]
### Steps to reproduce the problem starting from a fresh install

  1.
  2.
  3.

### Specifications

  - Version: 1.1-stable.527
  - Operating System: 
  - .Net/Mono runtime version:
  - Hardware configuration: 

#### Additional configuration notes
I know this subject was discussed back in 2014 but is it time to add native support for Node Red workflows. Obviously with Javascript support already built in to HG it would make a lot of sense to include this. I’m using Node Red successfully in Home Assistant and work flows make life so much easier

**Comment by tuicemen** [comment]
I don't mean to diminish this request nor to I wish to be perceived as me attacking you.
I'm just curious. You use Home Assistant but you ask for HG improvements so I wonder, What is it about HG that keeps you coming back? Do you just preferer the look and feel of HG or is it something else?

**Comment by mralapete** [comment]
I thought I’d woken a sleeping giant, as in Gene and he had come back with a response. Unfortunately not so far. 

I’m a little puzzled at your question and the fact that you think I may perceive it as an attack. Obviously it’s off topic but in response, in one word sentimentality, same reason why I still use X10.

HG was probably the first serious home automation application I used and that coupled with the healthy community that used to exist on the old HG forum it makes it difficult to abandon it. 

Yes I use Home Assistant along with a number of other home automation applications all communicating with each other including HG thankfully and will probably continue to do so. 

The built in X10 support in HG makes it an ideal companion for that technology and thankfully, unlike the old HG forum the contacts I made there continue today.

Hopefully I’ve answered you question thoroughly and here’s hoping that Gene replies with positive news on my request.

**Comment by bkenobi** [comment]
For those that don't know, Node Red is far and away superior to the visualization capabilities within HG.  Gene did a great job building his own system to store statistics but NR is on another level.  Having the ability to utilize such a powerful engine would be a great addition to HG.  I may look into how this could be done, but since Gene knows HG like the back of his hand, I'm sure this would be a simple question to answer:  Can node red be integrated into HG?

I'm sure the answer is yes, but for anyone other than Gene to provide the solution may be a monumental task!

**Comment by mralapete** [comment]
I’d imagined that this would have been on obvious choice for native integration a long time ago. 

I imagine an outgoing web hook from HG to NR wouldn’t be too difficult to organise but as you say having the HG blueprint would save a lot digging. 

Maybe if Gene is checking in occasionally to his GitHub he could give this subject some serious consideration.
