### ISSUE TITLE
widget manager not working

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#405]
### Expected behavior

moving widget  to stay in place prior to clicking save
### Actual behavior
you are able to drag a widget to a new location but once you release the mouse button it returns to its old location. saving makes no difference it still appears in old location

### Steps to reproduce the problem starting from a fresh install

  1. besure your on stable-8  and in the home screen
  2.select widget manager from actions tab
  3. cick and drag widget

### Specifications

  - Version: 1.3-stable.8
  - Operating System: raspbian buster
  - .Net/Mono runtime version:
  - Hardware configuration: pi cm15

#### Additional configuration notes
it is possible I'm missing a step here and that is why it is failing.

**Comment by mralapete** [comment]
What browser are you using to access HG

**Comment by genemars** [comment]
I've tested this on Firefox, Chromium and Chrome. No issues so far.

**Comment by tuicemen** [comment]
Ive only tested from my phone using edge and the samsung browser so guess ill have to try firefox next if I want to use this option

**Comment by tuicemen** [comment]
Just tested with chrome so  it is a browser issue
