### ISSUE TITLE
Revert  to previous build

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#406]
Would it be possible to have option to load an older build.  The current HG search and update reveils stable 8 available but loads  version 13-stable.6  if you go that route you can not load stable 8 manualy as HG sees the file as being older. In order to get 8 you must load a backup then do a manual install.  There are other instances where this would be handy.loading a back up doesn't always cut it or adds an extra step.

**Comment by mralapete** [comment]
Just do a manual update in the HG GUI. That's what the function is for. Release is working nice. Drag'n'drop works nicely.

**Comment by tuicemen** [comment]
If I do a manual update of 8 the update icon still displays an update is available. You can't do a manual update HG tells me current file is newer and won't  install the older version.

**Comment by mralapete** [comment]
No problem here.What are you using to access your HG server

**Comment by genemars** [comment]
As mentioned in the other issue, I've deleted release `v1.3-stable.6` and this should fix the issue.

**Comment by tuicemen** [comment]
@genemars thanks however this doesn't  allow me to revert to an older build infact this machine still sees stable 8 as older and wont install it. As a suggestion with the manual install when it does the check for older file have a popup asking if you wish to install the older version.
Im attempting to do thiswhile away so don't  have my backup handy not sure that it would install the older system version anyways.

**Comment by mralapete** [comment]
I strongly doubt you’ll achieve any of this from a phone if that’s what you are attempting.

**Comment by mralapete** [comment]
What you’ll need to do is grab the tarball and download it to a local machine. From there just point the HG restore in the GUI to your locally downloaded tarball and proceed with the restore. That will get version 8.

**Comment by tuicemen** [comment]
I was able to manualy update to 8 via my phone for my off grid place. I've not attempted to revert to an older version. My city place sits at version 6  and sees 8 as older due to how HG checks files. The issue maybe my phone or the browser I'm using. I'll get my wife to bring up my laptop and try with it. I believe it has my latest backup on it too. Stay tuned.

**Comment by tuicemen** [comment]
While I wait  can anyone revert their current HG version to even just the previous version?
I know restoring an old backup keeps the current version and just restores personal programs and widgets. Uninstalling HG and reinstalling an older version is a pain.

**Comment by mralapete** [comment]
Fine. This method is proven to work. The simplest method I suggested was to download https://github.com/genielabs/HomeGenie/releases/download/v1.3-stable.8/homegenie_1.3-stable.8.tgz to a local machine and do a manual upgrade via the HG GUI by pointing the upgrade to the locally downloaded release. This way even the yellow upgrade arrow disappears

**Comment by tuicemen** [comment]
I'm at 8 on one machine the method you stated is what I used. I'm looking to move **back** a build **not up** without having to uninstall and reinstall. 
Try https://github.com/genielabs/HomeGenie/releases/download/v1.3-stable.8/homegenie_1.3-stable.7.tgz  HG will not let you install it.

**Comment by tuicemen** [comment]
This issue/request got off topic and users responding were focusing more on installing the current  version. Since this is the case I'll close the issue.
