### ISSUE TITLE
 HG Update v1.3 r8. Everything working fine and Drag and Drop works well

### ISSUE THREAD

**Issue by mralapete** [genielabs/HomeGenie#407]
This is not an issue but just to let other users know I have successfully updated to the latest version of HG and all advertised features are working fine.The simplest method I suggest is to download https://github.com/genielabs/HomeGenie/releases/download/v1.3-stable.8/homegenie_1.3-stable.8.tgz to a local machine and do a manual upgrade via the HG GUI by pointing the upgrade to the locally downloaded release. This way even the yellow upgrade arrow disappears.

I have to say the drag and drop feature in the Widgets Manager is very neat and quite simple to use. Nice little touch @genemars

**Comment by tuicemen** [comment]
Thought you were using the BE addition?
What HG version did you update from?
I also ran the update this way but still get the yellow Update notification icon in top right corner. Maybe running a update check on version 8 triggers this false report.
I do like the drag and drop widget feature and the program options adds too.

**Comment by soxfan1966** [comment]
I just happened to pull up the HG web page on my phone (Pixel 4) and the page loads but I can no longer swipe up and down to move to the other components on the page.  Tapping seems to work OK.  I think it may be related to the drag and drop changes ?

**Comment by mralapete** [comment]
> Thought you were using the BE addition?
> What HG version did you update from?
> I also ran the update this way but still get the yellow Update notification icon in top right corner. Maybe running a update check on version 8 triggers this false report.
> I do like the drag and drop widget feature and the program options adds too.

Yes I do among other versions but this post relates to the above. Updated from HG v1.3 r7. All update notifications cleared and system is stable.System is fully updated now.This post was purely to reassure those who saw three Issues flash up in the Github and were holding off updating as a result.

**Comment by mralapete** [comment]
> I just happened to pull up the HG web page on my phone (Pixel 4) and the page loads but I can no longer swipe up and down to move to the other components on the page. Tapping seems to work OK. I think it may be related to the drag and drop changes ?

Possibly but device specific issues would be a separate matter I imagine. Maybe open a new Issue and log the problem.

**Comment by soxfan1966** [comment]
I submitted a new issue for the android swipe not working

**Comment by soxfan1966** [comment]
Looks like Gene just released version 1.3-stable 9 that fixes the drag and drop issue I reported on Android.  I am going to try and install it now.

**Comment by tuicemen** [comment]
Stable 9 fixed all my issues I had.

**Comment by soxfan1966** [comment]
I did the manual update (download the file, then use the Manual Update button.  It updated, and my About info shows version 1.3-stable 9 but the update arrow is still there and I tested on my Android and the swipe still does not work.

Tuicemen - did you do the manual update or Update Manager (auto?) update?  I was going to try the Update Manager way now and see if that works.

**Comment by soxfan1966** [comment]
I did the Update Manager approach and the Yellow Arrow (update notification) is gone and the About info shows I am version 1.3-stable 9.
So thats good.
However, the swipe up / down on my Android still does not work.  I will make a note on the issue I had opened for that - not sure if anyone else can confirm that it does / does not work.

**Comment by tuicemen** [comment]
@soxfan1966 i did the update manager route for 9 on both machines I can access since the manual update failed to remove the icon prior. As for your swipe issue. I find it eorks differently now but does work. I have to swipe up from the stats button or down from the top I can't  swipe from the center of screen as I could prior.
