### ISSUE TITLE
HG on Android - Pixel 4 - Chrome Browser = swiping not working

### ISSUE THREAD

**Issue by soxfan1966** [genielabs/HomeGenie#408]
### Expected behavior
Once HG loads you should be able to swipe up and down to see the modules.

### Actual behavior
With the update to 1.3 stable 8, swiping does not work any more.

### Steps to reproduce the problem starting from a fresh install

  1.  Pull up your HG web page on your android browser (Chrome)
  2. swipe up and/or down to try and move to a different module
  3. nothing happens, the screen stays in the same position

### Specifications

  - Version: 1.3 - stable 8
  - Operating System: 
  - .Net/Mono runtime version:
  - Hardware configuration: 
HG running on Pi
HG Web Page loaded on Android (Pixel 4 XL)

**Comment by soxfan1966** [comment]
Gene,
I just updated to version 1.3-stable 9 but the swipe up/down is still not working on my Android (Pixel 4 XL using latest Chrome Browser).

**Comment by soxfan1966** [comment]
I tried this on my wife's Android - she has an older Samsung Galaxy S9 and the swipe up / down works on her phone.

**Comment by genemars** [comment]
@soxfan1966 try clearing the browser cache on your phone.

**Comment by tuicemen** [comment]
Swiping I find works slightly different now you can't  swipe from the center of the screen.

**Comment by soxfan1966** [comment]
gene - clearing the browser cache on my phone seemed to do the trick, thanks (sorry, I should have thought of that and tried it).
