### ISSUE TITLE
HG version 1.3-8 = Using Chrome Inspection, Errors

### ISSUE THREAD

**Issue by soxfan1966** [genielabs/HomeGenie#409]
### Expected behavior
I was using the Chrome Inspect tool on my desktop computer to try and see where / why the update arrow was appearing still even though I have updated to ver 1.3-stable 8.

In doing so, I noticed some errors being displayed so I wanted to share them

### Steps to reproduce the problem starting from a fresh install

  1.  Load HG in Chrome on a Windows 10 Desktop
  2. Right click with your mouse and chose Inspect from the menu
  3. The console on the bottom displays the errors

### Specifications

  - Version: 1.3-stable 8
  - Operating System: 
     Windows 10
  - .Net/Mono runtime version:
  - Hardware configuration: 

#### Additional configuration notes

Here are the errors that were appearing:
webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "control_widgetsmanager_cancel" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "control_widgetsmanager_save" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "control_widgets_manager" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "analyze_delete_stat" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_editprogram_options_edit" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_editprogram_options_enable" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_editprogram_options_disable" is undefined.
2homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_editprogram_options_clone" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_updatemanager_manualupdate" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_location" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_latitude" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_longitude" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_setlocation" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_hostheaderis" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_hostheaderchange" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_temperature" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_dateformat" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_pickalocation" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_hostheaderheading" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_hostheaderchangenote" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_hostheadercancel" is undefined.
homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "configure_system_hostheaderchange" is undefined.
pages/control/widgets/tuicemen/tools/locales/en.json:1 Failed to load resource: the server responded with a status of 404 (Not Found)
homegenie.webapp.js?version=v1.3-stable.8:479 WARNING (Locales.LocalizeWidget): "pages/control/widgets/tuicemen/tools/locales/en.json" 404 Not Found
13homegenie.webapp.js?version=v1.3-stable.8:413 WARNING (Locales.GetLocaleString): "control_module_toggle" is undefined.

**Comment by genemars** [comment]
That's the expected behavior since some translations are missing. They will be added at some point.

**Comment by soxfan1966** [comment]
OK, thanks.  I will close this one out.
