### ISSUE TITLE
Install instructions for MacOS Catalina don't work

### ISSUE THREAD

**Issue by fracturedsoftware** [genielabs/HomeGenie#412]
I tried to install HomeGenie on a Mac with no luck. Mono 6.8.0.123 is installed.

After downloading homegenie_1.3-stable.10.tgz the first problem is that the actual instructions to start the server appear to be wrong. The instructions say to:

cd homegenie
./startup.sh

but there is no script at this location. The script appears to be in the DEBIAN folder instead.
I did the following instead:

cd homegenie/DEBIAN
./startup.sh

and a script started but all I get is a stream of mono errors:

sudo: /usr/local/bin/mono: command not found

I looked in that directory and there is no mono alias. 

At that point I gave up.

**Comment by genemars** [comment]
Try:
```
cd homegenie
mono HomeGenie.exe
```
