### ISSUE TITLE
HG18 OpenWeatherMap update does not allow COUNTRY designation[BUG]

### ISSUE THREAD

**Issue by helled** [genielabs/HomeGenie#422]
**Version**
Which HomeGenie version/OS/.NET framework version are you using. **(REQUIRED)**
 HG 18, BUSTER. Both updated as of 09 Sep 2020. Used HG17 to install HG18.

**Describe the bug**
Disabled previous OpenWeatherMap but did not delete it. Enabled new version. Then selected Edit. Tried my city, as used in previous version, and as soon as I began to type ",US", I was asked for HG ID and Password. After providing ID and Password, I first tabbed to API ID and provided. Then tabbed back to City and tried again this time without Country. It saved but after Service Restart and Pi reboot, the data would not update hours later. Also tried Houston, US and got the same results. Program was showing Enabled and with green status. Then I disabled new update and enabled old version of program. Ran well and updated date immediately. Pi with new HG18 ran well for 24 hours. Tried to replicate and found the new version continues to want my ID and Password but will not accept Country and will not update data.

**Code to Reproduce**
Write a small snippet to isolate your bug and could be possible to our team test. **(REQUIRED)**

**Expected behavior**
Allow introduction of City, Country.

**Screenshots/Stacktrace**
If applicable, add screenshots/stacktrace

**Additional context**

**Comment by mralapete** [comment]
HG 1.3 v18 has been withdrawn. Try v19 instead. OpenWeather working fine on v19. 

Try doing a fresh install of HG and restoring a recent backup. Sounds like your Configuration files may have been corrupted.
