### ISSUE TITLE
Python deprecated? [QUESTION]

### ISSUE THREAD

**Issue by bkenobi** [genielabs/HomeGenie#453]
I was just looking at the updates to the code and, when trying to determine if any of the bugs I've created issues for had been fixed, I noticed that Python appears to have been deprecated as of May 2021.  Did I read that correctly?  I don't use Python in my HA setup because it was not available when I wrote my code.  I'm not a fan of C# but used it out of necessity wishing Python had been an option.  If that was a design choice, I have to wonder what would have driven that since basically every hobbyist out there is using Python for the majority of their code.  I'm hoping I misread and it was intended to say the version of Python was deprecated in favor of the modern standard.

https://github.com/genielabs/HomeGenie/commit/1e72db268c1573e5212370a7384040188f99a279

![image](https://user-images.githubusercontent.com/6903751/211447486-da56103a-4ad7-43fb-8f18-4e7224d6ef01.png)

**Comment by EnGamma** [comment]
I'll  register a vote for maintaining Python support also, especially Python 3.

**Comment by homeautomate8** [comment]
I had notifications for this GitHub turned off and just came across this new HG 1.4 Beta. 

Are we to understand that from HG1.4 Python 1.4 is no longer supported. For anyone unsure up to this point it was in fact Iron Python that was deployed in HG. It was always slightly behind standard Python version wise. IIRC version 2.7. Iron Python 3.4 is now in current release.

Bearing in mind that many HG users would deploy Python quite extensively and Python is probably the biggest scripting language in use today, certainly for the tinkerer community am I reading correctly that from HG 1.4 onwards it is no longer supported.

**Comment by genemars** [comment]
Python automation programs are now back in `v1.4.0-beta.23`.
It's using latest IronPython 3.4.
Enjoy!

**Comment by EnGamma** [comment]
That's great, thank you.
