### ISSUE TITLE
[QUESTION] has the old UI been rendered inaccessable?

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#455]
I've been playing with different builds of HomeGenie beta and it seems access to the old ui is unavailable. Am I missing something? 
I don't mind the new UI but untill it supports cameras and custom programs and widgets it really is of no use to me. The attraction of HomeGenie was the ability to create custom programs and widgets. The inability to use these in the new UI means few will upgrade.

**Comment by soxfan1966** [comment]
Which of the beta versions have you tried?  I was going to try updating
myself but need to find the time to do it

**Comment by tuicemen** [comment]
I've tried 3  as Gene has been busy updating By the time I got one installed and a old back up installed 2 new versions were out. I'm at the cottage and was going to install the newest but I couldn't get the service to start I believe I have ver 10 install at my city place. Heading back today so I'll see about updating to 13 there.
The versions I've tested are not the core but .net versions as they were installed on 32 bit Pis.

**Comment by tuicemen** [comment]
I just updated from beta 10 to 13 and still see no way to navigate to the old UI.
the old UI use to be at /hg/html/index.html but this throws a 404 -not found error
Also no way to add cameras like in the Alpha builds.
And no way to add user created widgets or programs
Maybe it is just the net472 build that is lacking these.

**Comment by tuicemen** [comment]
Just loaded the netcore(64 bit) beta 15 build to my pi 3b+ and it's missing the same stuff maybe even more☹
