### ISSUE TITLE
Widgets don't stay saved to new location (1.4.0-beta.20)

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#459]
**Version**
latest version 1.4.0-beta.20 both 32 and 64 bit versions tested on my pi 3b+
**Describe the bug**
unable to move  (re-arrange widgets) and them stay saved to that location.
**Code to Reproduce**
Write a small snippet to isolate your bug and could be possible to our team test. **(REQUIRED)**

**Expected behavior**
once widgets have been moved they stay there for next load of HG
**Screenshots/Stacktrace**
If applicable, add screenshots/stacktrace

**Additional context**
widgets do move to new location however if you refresh the screen or restart HG they are not where they should be but back in there previously moved position.
this happens for both newly added widgets as well as old added widget.
this may be Browser specific but happens in the Edge browser.

**Comment by tuicemen** [comment]
While attempting to recreate this bug on my Samsung galaxy  OS it seemed to work untill my 4th move then HG said everything wasn't configured and sent me to the initial setup screen again :( .
this was with the net 472 32 bit HG.
luckily the desktop screens are different on different device OSs (not sure why that is) as my Edge browser HG is still OK

**Comment by tuicemen** [comment]
Strangely after several hours HG appeared setup again on my android, however widgets were still not in the moved position. Tried the Edge browser on the Android with same results. (Widgets move to new location but don't  get saved to that location)😖😖😖

**Comment by genemars** [comment]
Let me know if this happen again with latest release.

**Comment by tuicemen** [comment]
With latest release beta 24 this still happens on my windows 10 pc using the Edge browser. HG is running on a raspi 3b+. This happens with both the 32 and 64 bit versions.
If I use my phone to edit my widget locations they stay even using the Edge browse on the Phone. I tried clearing the cache and closing the browser after a change on the PC but this doesn't help .

**Comment by genemars** [comment]
So, is this problem occurring only on Edge browser?

**Comment by tuicemen** [comment]
Yes only with the Edge browser on Windows pc
