### ISSUE TITLE
[SUGGESTION] additional custom widget size option

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#460]
**Is your feature request related to a problem? Please describe.**
the current size option for this is ok for most things however some old time widgets needed a custom size or at least to display full width of HG desktop
**Describe the solution you'd like**
I'd like to see one more size option that allowed for full width of the HG screen current large height is ok
perhaps call it Xlarge

**Describe alternatives you've considered**
scroll bars do appear but some things get jumbled as seen in attached

**Additional context**
![sample](https://user-images.githubusercontent.com/25393840/217383373-36f88b6b-9533-4ea4-a54f-853bfdf585ce.png)

**Comment by genemars** [comment]
By leaving the size field to "Not set" should now allow any custom size.

**Comment by tuicemen** [comment]
Ok so how would one custom size the widget?

**Comment by genemars** [comment]
> Ok so how would one custom size the widget?

You can set the size in the widget's html or css.

**Comment by tuicemen** [comment]
But wouldn't that change all widgets using this to that size if the size field was left as not set?

**Comment by genemars** [comment]
Each added widget has its own settings.

**Comment by tuicemen** [comment]
Ok thanks
