### ISSUE TITLE
BE VERY WARY!

### ISSUE THREAD

**Issue by hs6666** [genielabs/HomeGenie#462]
... no answer to any qustions, and issues closed with no explanation by genemars

at the same time a new beta is posted today with no attached notes/explanation etc..

I'd be very wary of this project from now on and would strongly urge people to not install the latest builds

**Comment by tuicemen** [comment]
There are a lot of unanswered questions.
The current beta builds are more like alfa ones.
There are a few of us testing these builds and with the Homegenie.club forum now gone.there realy isn't anyplace to discuss the new HG.
There are a few HG users on the x10 forum but I believe most are on the 13 stable or older version. Moving to 14 is going to be a big learning curve for many. With no documentation as yet.

**Comment by genemars** [comment]
Have you read this?

https://github.com/genielabs/HomeGenie/blob/master/CONTRIBUTING.md

and maybe this?

https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette

**Comment by mralapete** [comment]
> ... no answer to any qustions, and issues closed with no explanation by genemars
> 
> at the same time a new beta is posted today with no attached notes/explanation etc..
> 
> I'd be very wary of this project from now on and would strongly urge people to not install the latest builds

You’ve invoked the ire of The Politburo. Discussion is not encouraged with the developer.

Discussion has now been shutdown. I have already been told to go elsewhere and use an alternative to HG which I’d already done anyway. 

From what I can see it’s down to one tester and from watching Issues being opened/closed/reopened I’d safely say the developer is down to a team of one. Such a shame as right up to v1.3 19 stable HG ran quite smoothly. 

GitHub is no place to hold discussions anyway and as the last resort the HG Club has been pulled effectively there’s no place left to discuss HG. 

Good luck to Gene with this project and anyone who is testing it.

**Comment by genemars** [comment]
By the way, the log of this release commit is here:
--> https://github.com/genielabs/HomeGenie/commit/aa403b85358e3c9c38358c09078967b7153ec552
