### ISSUE TITLE
VLP programing Question

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#463]
Is there currently a way to add a RF trigger for these?
For example on a X10 security flob disarm signal to disarm the security system.
I don't see a way to add any RF signal

**Comment by genemars** [comment]
Here is a short video that shows how to handle RF signals and module events in general.
To disarm the security system you can the use the custom command after selecting the "Security System" module.
The command in this case is `Control.ArmAway` or `Control.ArmHome` and `Control.Disarm`.
I think also the two pre-built commands in the Control palette, `On` and `Off`, will arm/disarm the security module.

[Video del 06-03-2023 14:11:13.webm](https://user-images.githubusercontent.com/6654265/223129694-d407f426-666c-4879-9026-4b7086baa351.webm)

**Comment by tuicemen** [comment]
Thanks that helps a lot.

**Comment by tuicemen** [comment]
Is there currently away to send RF RawData as well with a VLP Program?
Example send a panic code to the X10 security console to trigger the Alarm and reflect this in the HG security system.

**Comment by tuicemen** [comment]
Thanks.
