### ISSUE TITLE
 AVG or Avast block HomeGenie.exe (Windows) due to "idp generic" false positive

### ISSUE THREAD

**Issue by dakriege** [genielabs/HomeGenie#469]
**Version**
Which HomeGenie version/OS/.NET framework version are you using. **(REQUIRED)**
1.4.0-beta.55
**Describe the bug**
Chrome blocks the download indicating a suspicious file when you select the Windows installer on your website
Downloaded directly from GitHub
Installed on Windows 10 PC
When trying to run homegenie.exe,  AVG antivirus triggers a virus fault on idp.generic
The service starts then shortly after it starts it faults on a virus detected
The program ran once and I was able configure a ZWave node. 
**Expected behavior**
Service starts and works without being detected as virus
**Screenshots/Stacktrace**
If applicable, add screenshots/stacktrace

**Additional context**

**Comment by genemars** [comment]
I searched the web for this *idp.generic* issue and this is what found:

> I have found a fix for IDP generic caused due to AVG or Avast. [idp generic](https://techwhose.com/what-is-idp-generic-and-how-to-remove-it/) is caused due to outdated software files of Avast or AVG, updating it to the latest version will help it to solve the issue.

Source: [Unity Forum post](https://forum.unity.com/threads/build-triggering-avg-idp-generic-virus-warning.721964/#:~:text=idp%20generic%20is%20caused%20due,it%20to%20solve%20the%20issue.)
