### ISSUE TITLE
Ideas for thermostat

### ISSUE THREAD

**Issue by annuncimarco** [genielabs/HomeGenie#50]
Hi Genie,
some ideas for thermostat:
- add a range temperature, near set point  with step of 0.25 or 0.5 degree for not start and stop the boiler every 5 minutes,  when the temperature changed fast, for example open a window.
  Example: range from 20.5 to 22.5, heating to 22.5 then "PendingHeat", when the temperature go down to 20.5, start again to heating to 22.5 then "PendingHeat"
- add icon like "user" or "away", integrated with PIR sensor, when people are out, after  time "X", change the boiler  in OFF state or awaiting of new state like start again to hour "X"
- add an icon "program" with a simple day/week selection, possibility to change temperature every 1/2 hours, copy and paste day program or possibility to select multiple day when the program is the same every day

thank
Marco

P.S:
next week I hope to start to use the APP for thermostat in my home, when I wired all temperature sensors in the rooms and connect the relay to boiler  :)

**Comment by genielabs** [comment]
new Enahnced Thermostat program has a timetable+calendar facility
