### ISSUE TITLE
Widgets show temperature in Farenheit when they should be in Centegrate

### ISSUE THREAD

**Issue by RichCattell** [genielabs/HomeGenie#76]
This appears to be an intermittant bug, and im not sure when or what causes it to happen, but...
all of my widgets that show temperature, i.e. thermostats and my 3-in1 motion sensors all now show their temperature in Farenheit whereas they used to show in Centigrade. However the values shown in the group list still show in Centigrade.

**Comment by genielabs** [comment]
This should be solved by now. I'm closing it, just reopen if the issue is still there.

**Comment by RichCattell** [comment]
Im still getting this issue in r474, so it looks as though his hasn't been fixed yet.

**Comment by genielabs** [comment]
duplicate #196
