### ISSUE TITLE
Support for battery powered z-wave thermostat devices

### ISSUE THREAD

**Issue by RichCattell** [genielabs/HomeGenie#77]
The current implementation appears to assume that a thermostat device is always awake and able to receive set-point messages from HomeGenie when temperature is changed in a Thermostat widget.
Could support be added to allow set-point messages to be sent to thermostat devices on wakeup?

I have a battery powered thermostat (Horstmann HRT4-ZW) and when i try to change the set point in the HomeGenie widget i get a "Node Response Timeout!" message. The minimum wake up time i can set on this device is 256 seconds..

**Comment by Raider2000** [comment]
I also use some battery powered Danfoss Thermostats and have similar issues as Rich. I therefore also would like to ask for an implementation of the message queue.
