### ISSUE TITLE
Switch/Light/etc doesn't send ON command module is already ON

### ISSUE THREAD

**Issue by bkenobi** [genielabs/HomeGenie#85]
If a module (switch, light, maybe others) is in the ON state and you try to select "ON" in the interface, HG ignores the command.  If the module is in the OFF state and you select "OFF", the command is sent.  I would like the ON command to send even if the module is in the ON state already.

This is an issue for 2 reasons.
1) X10 and other modules can become out of sync and a manual command should be possible to set the state where they should be.
2) In the case of a switch, I would like to be able to send multiple ON and OFF commands in a row.

**Comment by genielabs** [comment]
the command are always sent despite of the status. there's no such check in hg.

**Comment by bkenobi** [comment]
I didn't check the mono log, just my Activity and standard HG log.  I'll look at mono and try again.

**Comment by bkenobi** [comment]
You are correct, sorry.  The interface isn't updated, but it is definitely processing all commands in the code as viewed in the mono output.
