### ISSUE TITLE
User scripts require compile after restore

### ISSUE THREAD

**Issue by bkenobi** [genielabs/HomeGenie#86]
When restoring a configuration after a manual HG installation (installing a testing version for example), if programs are selected for restoration they do not work.  It appears that the program .dll is restored but the code remains yellow in the interface rather than green.  The only resolution I have found is to manually compile each code.  I have tried restarting both the HG service and the Raspi and I do not believe this resolves the issue.

**Comment by genielabs** [comment]
I'm looking into this issue right now... could replicate. Thanks!

**Comment by genielabs** [comment]
Fixed!

**Comment by bkenobi** [comment]
Great, thanks!
