### ISSUE TITLE
X10 RF button down/up appear the same

### ISSUE THREAD

**Issue by bkenobi** [genielabs/HomeGenie#87]
When using an X10 RF transmitter (e.g., HR12A Palm Pad) the controller sends a signal that includes the button position (up or down).  This can be seen from ActiveHome Pro as a reference.  In HG, when pressing the button down and then releasing, there are multiple events received.  If the button is held very briefly, the commands it sees are (B6 ON as an example):
B6 ON Button down
B6 ON Button up

HG should either ignore the button up command or differentiate between the different commands in some way.

**Comment by genielabs** [comment]
dunno what to do with this, so I'm closing it.
