### ISSUE TITLE
Alarm UI Label overlap

### ISSUE THREAD

**Issue by juszissguy** [genielabs/HomeGenie#89]
Adding a '<style>div.ui-slider-switch { width: 7.5em }</style>' in BaseFiles/Common/html/pages/control/widgets/homegenie/generic/securitysystem.html seems to work

Before & After
![screen shot 2015-01-10 at 1 05 30 am](https://cloud.githubusercontent.com/assets/10180601/5690728/e805643e-9864-11e4-8a4d-e4f06443c9a7.png)

**Comment by genielabs** [comment]
where is this supposed to be added?

**Comment by genielabs** [comment]
fixed in r471.
