### ISSUE TITLE
GetDateEndianType does not necessarily correlate to Fahrenheit usage

### ISSUE THREAD

**Issue by tareko** [genielabs/HomeGenie#92]
After being very annoyed by why I can't get rid of fahrenheit, I discovered that HG makes a silly assumption. From `/BaseFiles/Common/html/pages/control/widgets/homegenie/generic/thermostat.json`

```if (HG.WebApp.Locales.GetDateEndianType() == 'M') displayUnit = 'Fahrenheit';```

At least in Canada, this is definitely not true.

Can this not be a user-specified option that defaults to the international standard of Celsius??

For me, I fixed this problem by simply doing:

```grep -R "GetDateEndianType" * | grep "Fahrenheit"```

and then removing all of the instances.

tarek : )

**Comment by genielabs** [comment]
a user-specified option would be a good solution. mark this as enhancement.

**Comment by gitbjo** [comment]
Hi,

I agree, this should be a setting for the widget. I have the same problem in Switzerland.

gitbjo.

**Comment by genielabs** [comment]
duplicate #196
