### ISSUE TITLE
X10 Incorrect Commands CM15Pro

### ISSUE THREAD

**Issue by pim555** [genielabs/HomeGenie#95]
Hi All,

As described in the topic below
http://www.homegenie.it/forum/index.php?topic=579.0

My set-up is HG r453 on raspberry PI with CM15Pro running in the Netherlands (220V).

Issue is best described as if the X10 command executed from HG UI or script is also executed for the house/unit code addressed during the previous command. For example, if A3 ON is sent while previously A7 OFF was sent, A3 will be switched on but also A7. This behavior is consistent across several modules and addresses. I am not able to reproduce using Mochad on RPI, AHB and Homeseer on Windows. HG on Windows does show the same symptoms.

It looks like HG has an X10 implementation for CM15Pro that is causing this. User Bkenobi tried to reproduce using CM15a but is not able to. Looks like it is an isolated issue for CM15Pro (EU Version).

Regards
Pim

**Comment by genielabs** [comment]
Sorry could not replicate the issue described but the one about the first command sent not performed. So i fixed this one.
Can you provide more details about how to reproduce this issue?
Sequence of commands to send with AHP and with HG to see the different behaviour? I tried also comparing input/output from AHP with HG... and they are the same (tried ON/OFF on two different units repeatedly).

**Comment by pim555** [comment]
I can consistently reproduce by for example below sequence in the HG UI (home/unit code is arbitrary):

1. press ON button for device A1, A1 switches on (NORMAL)
2. press ON button for device A2, A2 switches on (NORMAL)
3. press OFF button for device A1, A1 and A2 switch off (WRONG)

Any other sequency where the second command contains a different address from the first (for example step 2 and 3 above) and the command is opposite from state result in both devices being controlled.

It looks like (hypothetical) every command is also executed for the address selected in the previous command. However, if the state of the device controlled in the previous action does not change, you would not see any effect. For example, step 2 above would potentially also turn on device A1 but since that is already on, you will not notice. In step 3, the state of device A2 is ON so since A2 is also (wrongly) selected, it is also switched off.

The same command sequency from AHB UI would switch off A1 only in step #3 as expected. Same when using Mochad on RPI.

Hope this clarifies.

Regards
Pim.

**Comment by genielabs** [comment]
see my reply here:
http://www.homegenie.it/forum/index.php?topic=579.msg3669#msg3669
Cheers,
g.
